// ===========================================================================
// nfpa-report.js — NFPA-style hydraulic calculation report (Phase 3).
//
// PURE transform: takes a `solveNetwork()` result (the connected-network
// Hazen-Williams solve over the Phase-2 topology) and produces a structured,
// printable NFPA-format hydraulic calculation report:
//
//   • summary sheet  — system demand (gpm @ psi), available supply, safety
//                      margin, friction/elevation/velocity-pressure breakdown,
//                      design basis, hazard, K-factor.
//   • node analysis  — one row per junction: Ref / Elevation / K / Pressure /
//                      Flow (the classic NFPA "node analysis" table).
//   • pipe data      — one row per pipe segment: From→To / nominal dia /
//                      length + fitting Le / C-factor / flow / friction loss
//                      (the classic NFPA "pipe data" table).
//
// This is an ENGINEERING AID, NOT a PE-stamped / AHJ-approved calc. The header
// carries that disclaimer. The numbers are exactly what the validated solver
// computed — this module only re-shapes them into report rows; it adds NO new
// physics (so it stays exactly as honest / PARTIAL as the underlying solve).
//
// Golden-tested in tests/nfpa-report.test.js against a hand-built solve result.
// ===========================================================================

export const REPORT_DISCLAIMER =
  'ENGINEERING AID — NOT a PE-stamped or AHJ-approved hydraulic calculation. '
  + 'Generated by a connected-network Hazen-Williams demand/pressure solve over '
  + 'the design model. Verify against the sealed hydraulic calculation before '
  + 'permit submission. NOT AutoSPRINK. NOT a substitute for a licensed designer.';

const HAZARD_LABELS = {
  light: 'Light Hazard',
  ordinary: 'Ordinary Hazard',
  'ordinary-1': 'Ordinary Hazard Group 1',
  'ordinary-2': 'Ordinary Hazard Group 2',
  extra: 'Extra Hazard',
  'extra-1': 'Extra Hazard Group 1',
  'extra-2': 'Extra Hazard Group 2',
};

function round(n, dp = 2) {
  if (n == null || !isFinite(n)) return n == null ? null : n;
  const f = 10 ** dp;
  return Math.round(n * f) / f;
}

/** Short stable reference label for a node key (the first 12 chars of the key). */
function nodeRef(key, idx) {
  if (typeof key === 'string' && key.length) {
    // keys look like "x,y,z" rounded — keep them readable but compact
    return key.length > 16 ? key.slice(0, 16) : key;
  }
  return `N${idx + 1}`;
}

/** Elevation (ft) for a node from its point. Plan is Y-up; Z is elevation. */
function nodeElevationFt(node) {
  if (!node) return 0;
  if (node.pt && typeof node.pt === 'object') {
    // pt may be {x,y,z} (true-scale ft). NFPA elevation = vertical height = z.
    const z = node.pt.z != null ? node.pt.z : (Array.isArray(node.pt) ? node.pt[2] : 0);
    return round(Number(z) || 0, 2);
  }
  return 0;
}

/**
 * Build the NFPA hydraulic report from a solveNetwork() result.
 *
 * @param {object} solve  result from solveNetwork()/solveWithUpsizing().final
 * @param {object} [meta] optional report metadata
 *   - projectName, system, designer, date
 *   - hazard ('ordinary' | 'extra' | ...)
 *   - densityGpmFt2, designAreaSqFt (from remote-area, when available)
 *   - kFactor (override)
 * @returns {object} report with {hasSummary, summary, nodeRows, pipeRows,
 *   nodeCount, pipeCount, meta, disclaimer, generatedAt}.
 */
export function buildHydraulicReport(solve, meta = {}) {
  const hazardKey = meta.hazard || null;
  const hazardLabel = hazardKey ? (HAZARD_LABELS[hazardKey] || hazardKey) : null;

  // --- Summary sheet -------------------------------------------------------
  // The headline NFPA "system demand vs supply" block. Every number here comes
  // straight from the validated solve; we only format + label it.
  const hasSolve = !!solve && typeof solve === 'object'
    && solve.demandGpm != null && solve.requiredPsi != null;

  let summary = null;
  if (hasSolve) {
    // Mirror the solver's already-rounded values directly — do NOT re-round and
    // recompute (that introduces a rounding drift away from the validated solve).
    const available = solve.availablePsi != null ? Number(solve.availablePsi) : null;
    const required = Number(solve.requiredPsi);
    const safety = solve.safetyMargin != null ? Number(solve.safetyMargin)
      : (available != null ? round(available - required, 3) : null);
    const demandMet = solve.demandMet != null ? solve.demandMet
      : (available != null ? available >= required : null);
    summary = {
      // demand — mirror the solver's already-rounded values (no re-round drift).
      demandGpm: Number(solve.demandGpm),
      requiredPsi: required,
      minHeadPressurePsi: solve.minHeadPressurePsi != null ? Number(solve.minHeadPressurePsi) : null,
      // supply
      availablePsi: available,
      safetyMarginPsi: safety,
      demandMet,
      // pressure breakdown (psi)
      frictionLossPsi: solve.frictionLossPsi != null ? Number(solve.frictionLossPsi) : null,
      elevationPsi: solve.elevationPsi != null ? Number(solve.elevationPsi) : null,
      velocityPressurePsi: solve.velocityPressurePsi != null ? Number(solve.velocityPressurePsi) : null,
      // fitting equivalent length consumed on the remote path
      fittingLeFt: solve.fittingLe && solve.fittingLe.totalEquivFt != null
        ? Number(solve.fittingLe.totalEquivFt) : 0,
      // counts + design context
      headsTotal: solve.headsTotal != null ? solve.headsTotal : null,
      headsFlowing: solve.headsFlowing != null ? solve.headsFlowing : null,
      remotePathLengthFt: solve.remotePathLengthFt != null ? Number(solve.remotePathLengthFt) : null,
      remoteHeadFlowGpm: solve.remoteHeadFlowGpm != null ? Number(solve.remoteHeadFlowGpm) : null,
      kFactor: meta.kFactor != null ? round(Number(meta.kFactor), 2)
        : (solve.kFactor != null ? round(Number(solve.kFactor), 2) : null),
      cFactor: solve.C != null ? Number(solve.C) : null,
      pipeCount: solve.pipeCount != null ? solve.pipeCount : null,
      nodeCount: solve.nodeCount != null ? solve.nodeCount : null,
      maxVelocityFps: solve.maxVelocityFps != null ? Number(solve.maxVelocityFps) : null,
      minNodePressurePsi: solve.minNodePressurePsi != null ? Number(solve.minNodePressurePsi) : null,
      conservationOk: solve.conservationOk === true,
      designBasis: solve.designBasis || null,
      designBasisNote: solve.designBasisNote || null,
      // human-readable design-basis label: distinguishes the NFPA-13 most-remote
      // AUTO-selected design area from a user-drawn area and the all-heads-open
      // worst-case envelope, so the report header reads honestly.
      designBasisLabel: (solve.designBasis === 'remote-area-subset')
        ? (meta.remoteAreaAutoSelected
          ? 'NFPA-13 remote-area design demand (auto-selected most-remote area)'
          : 'NFPA-13 remote-area design demand (user-drawn area)')
        : 'all-heads-open worst-case envelope',
      remoteAreaAutoSelected: meta.remoteAreaAutoSelected === true,
      remoteAreaFlowingHeads: meta.remoteAreaFlowingHeads != null ? meta.remoteAreaFlowingHeads : null,
      // remote-area design context (when supplied via meta)
      hazard: hazardKey,
      hazardLabel,
      densityGpmFt2: meta.densityGpmFt2 != null ? round(Number(meta.densityGpmFt2), 3) : null,
      designAreaSqFt: meta.designAreaSqFt != null ? round(Number(meta.designAreaSqFt), 1) : null,
      // honest convergence flags carried up to the summary
      hardyCrossBalanced: solve.hardyCrossBalanced === true,
      loopCount: solve.loopCount != null ? solve.loopCount : 0,
    };
  }

  // --- Node analysis table -------------------------------------------------
  // One row per junction: Ref / Elev / K / P / Q. The solver already produced
  // per-node pressure/flow (forward demand-fixed tree walk); we attach the K
  // factor (only nodes WITH heads have a K) and elevation.
  const nodeRows = [];
  const nodes = Array.isArray(solve && solve.nodes) ? solve.nodes : [];
  nodes.forEach((nd, i) => {
    const hasHead = (nd.headCount || 0) > 0;
    nodeRows.push({
      ref: nodeRef(nd.key, i),
      key: nd.key,
      elevationFt: nodeElevationFt(nd),
      // K-factor only applies at sprinkler nodes; junctions show null.
      kFactor: hasHead
        ? (meta.kFactor != null ? round(Number(meta.kFactor), 2)
          : (solve.kFactor != null ? round(Number(solve.kFactor), 2) : null))
        : null,
      // mirror the solver's already-rounded node pressure (no re-rounding drift).
      pressurePsi: nd.pressurePsi != null ? Number(nd.pressurePsi) : null,
      // discharge flow at the node: head discharge if a sprinkler, else the
      // through-flow on its feeding pipe (NFPA node-analysis "Q" column).
      flowGpm: hasHead
        ? Number(nd.headFlowGpm != null ? nd.headFlowGpm : nd.flowGpm) || 0
        : Number(nd.flowGpm) || 0,
      headCount: nd.headCount || 0,
      isSource: nd.isSource === true,
      isRemote: nd.isRemote === true,
      velocityFps: nd.velocityFps != null ? round(Number(nd.velocityFps), 2) : null,
    });
  });

  // --- Pipe data table -----------------------------------------------------
  // One row per pipe segment: From→To / dia / length + Le / C / flow / loss.
  // The solver reports per-edge friction + velocity for every tree edge; the
  // worst-path edges additionally carry the fitting Le that entered friction,
  // so we merge that Le onto the matching edge rows.
  const pipeRows = [];
  const edges = Array.isArray(solve && solve.edgeResults) ? solve.edgeResults : [];
  // index worst-path fitting Le by edge id so we can show the Le that the solve
  // actually consumed on each remote-path segment.
  const leByEdge = new Map();
  const wp = Array.isArray(solve && solve.worstPath) ? solve.worstPath : [];
  for (const seg of wp) {
    if (seg && seg.edge != null) leByEdge.set(seg.edge, Number(seg.fittingLeFt) || 0);
  }
  edges.forEach((e, i) => {
    // mirror the solver's already-rounded edge values (no re-rounding drift).
    const leFt = leByEdge.has(e.edge) ? Number(leByEdge.get(e.edge)) || 0 : 0;
    const lengthFt = Number(e.lengthFt) || 0;
    pipeRows.push({
      ref: `P${i + 1}`,
      pipeIdx: e.pipeIdx != null ? e.pipeIdx : null,
      from: e.from != null ? e.from : (e.a != null ? e.a : null),
      to: e.to != null ? e.to : (e.b != null ? e.b : null),
      fromKey: e.a != null ? e.a : null,
      toKey: e.b != null ? e.b : null,
      diameterIn: Number(e.diameterIn) || 0,
      lengthFt,
      fittingLeFt: leFt,
      effectiveLengthFt: round(lengthFt + leFt, 3),
      cFactor: solve.C != null ? Number(solve.C) : null,
      flowGpm: Number(e.flowGpm) || 0,
      velocityFps: Number(e.velocityFps) || 0,
      frictionLossPsi: Number(e.frictionPsi) || 0,
      overVelocity: e.overVelocity === true,
    });
  });

  return {
    // CHUNK contract: __hfPhase3.report -> { hasSummary, nodeRows, pipeRows }
    hasSummary: summary != null,
    summary,
    nodeRows,
    pipeRows,
    nodeCount: nodeRows.length,
    pipeCount: pipeRows.length,
    meta: {
      projectName: meta.projectName || 'HaloFire AutoSPRINK clone — design model',
      system: meta.system || 'Wet-pipe sprinkler system',
      designer: meta.designer || null,
      date: meta.date || null,
      hazard: hazardKey,
      hazardLabel,
    },
    disclaimer: REPORT_DISCLAIMER,
    generatedAt: meta.generatedAt || null,
  };
}

/**
 * Render the report to a self-contained printable HTML string (for export /
 * print preview). NFPA-style: disclaimer header, summary block, node-analysis
 * table, pipe-data table. Pure string build — no DOM, no side effects.
 */
export function renderReportHtml(report, opts = {}) {
  if (!report) return '';
  const esc = (s) => String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const s = report.summary;
  const m = report.meta || {};
  const gen = report.generatedAt || opts.generatedAt || '';

  const summaryHtml = s
    ? `<table class="kvt">
        <tr><th>System demand</th><td><b>${s.demandGpm} gpm</b> @ <b>${s.requiredPsi} psi</b> required</td></tr>
        <tr><th>Available supply</th><td>${s.availablePsi == null ? '—' : s.availablePsi + ' psi'}</td></tr>
        <tr><th>Safety margin</th><td class="${s.demandMet === false ? 'bad' : 'good'}">${s.safetyMarginPsi == null ? '—' : (s.safetyMarginPsi >= 0 ? '+' : '') + s.safetyMarginPsi + ' psi'} ${s.demandMet == null ? '' : (s.demandMet ? '(MET)' : '(NOT MET)')}</td></tr>
        <tr><th>Min head pressure</th><td>${s.minHeadPressurePsi == null ? '—' : s.minHeadPressurePsi + ' psi'}</td></tr>
        <tr><th>Friction loss</th><td>${s.frictionLossPsi == null ? '—' : s.frictionLossPsi + ' psi'}</td></tr>
        <tr><th>Elevation</th><td>${s.elevationPsi == null ? '—' : s.elevationPsi + ' psi'}</td></tr>
        <tr><th>Velocity pressure</th><td>${s.velocityPressurePsi == null ? '—' : s.velocityPressurePsi + ' psi'}</td></tr>
        <tr><th>Fitting equiv. length</th><td>${s.fittingLeFt} ft (NFPA-13 Le, remote path)</td></tr>
        <tr><th>K-factor</th><td>${s.kFactor == null ? '—' : s.kFactor}</td></tr>
        <tr><th>C-factor (Hazen-Williams)</th><td>${s.cFactor == null ? '—' : s.cFactor}</td></tr>
        <tr><th>Heads flowing</th><td>${s.headsFlowing == null ? '—' : s.headsFlowing} of ${s.headsTotal == null ? '—' : s.headsTotal}</td></tr>
        <tr><th>Hazard / density</th><td>${m.hazardLabel ? esc(m.hazardLabel) : '—'}${s.densityGpmFt2 != null ? ' · ' + s.densityGpmFt2 + ' gpm/ft²' : ''}${s.designAreaSqFt != null ? ' over ' + s.designAreaSqFt + ' ft²' : ''}</td></tr>
        <tr><th>Design basis</th><td>${esc(s.designBasisLabel || s.designBasis || '—')}${s.remoteAreaFlowingHeads != null ? ' · ' + s.remoteAreaFlowingHeads + ' heads' : ''}</td></tr>
        <tr><th>Flow conservation</th><td class="${s.conservationOk ? 'good' : 'bad'}">${s.conservationOk ? 'OK (ΣQ balanced at every node)' : 'CHECK'}</td></tr>
      </table>`
    : '<p class="muted">No solve available — generate a layout and solve hydraulics.</p>';

  const nodeRowsHtml = report.nodeRows.map((r) =>
    `<tr${r.isRemote ? ' class="remote"' : (r.isSource ? ' class="source"' : '')}>`
    + `<td>${esc(r.ref)}${r.isSource ? ' (SUPPLY)' : (r.isRemote ? ' (REMOTE)' : '')}</td>`
    + `<td class="num">${r.elevationFt}</td>`
    + `<td class="num">${r.kFactor == null ? '—' : r.kFactor}</td>`
    + `<td class="num">${r.pressurePsi == null ? '—' : r.pressurePsi}</td>`
    + `<td class="num">${r.flowGpm}</td></tr>`).join('');

  const pipeRowsHtml = report.pipeRows.map((r) =>
    `<tr${r.overVelocity ? ' class="over"' : ''}>`
    + `<td>${esc(r.ref)}</td>`
    + `<td>${r.from == null ? '—' : esc(r.from)} → ${r.to == null ? '—' : esc(r.to)}</td>`
    + `<td class="num">${r.diameterIn}</td>`
    + `<td class="num">${r.lengthFt}${r.fittingLeFt ? ' + ' + r.fittingLeFt : ''}</td>`
    + `<td class="num">${r.cFactor == null ? '—' : r.cFactor}</td>`
    + `<td class="num">${r.flowGpm}</td>`
    + `<td class="num">${r.velocityFps}</td>`
    + `<td class="num">${r.frictionLossPsi}</td></tr>`).join('');

  return `<!doctype html><html><head><meta charset="utf-8">
<title>NFPA Hydraulic Calculation Report — ${esc(m.projectName || '')}</title>
<style>
  body{font:13px/1.5 Inter,system-ui,Arial,sans-serif;color:#111;margin:24px;background:#fff}
  h1{font-size:18px;margin:0 0 2px}h2{font-size:14px;margin:18px 0 6px;border-bottom:1px solid #ccc;padding-bottom:3px}
  .disclaimer{background:#fff8e1;border:1px solid #f59e0b;color:#92400e;padding:8px 10px;border-radius:6px;font-size:11px;margin:8px 0 14px}
  .meta{font-size:11px;color:#555;margin-bottom:6px}
  table{border-collapse:collapse;width:100%;font-size:12px}
  th,td{border:1px solid #d1d5db;padding:4px 7px;text-align:left}
  th{background:#f3f4f6}.num{text-align:right;font-variant-numeric:tabular-nums}
  .kvt th{width:200px}.good{color:#15803d;font-weight:600}.bad{color:#b91c1c;font-weight:600}
  tr.source td{background:#eff6ff}tr.remote td{background:#fef2f2}tr.over td{background:#fee2e2}
  .muted{color:#888}
  @media print{body{margin:0}.disclaimer{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style></head><body>
<h1>NFPA Hydraulic Calculation Report</h1>
<div class="meta">${esc(m.projectName || '')} · ${esc(m.system || '')}${m.designer ? ' · ' + esc(m.designer) : ''}${m.date ? ' · ' + esc(m.date) : ''}${gen ? ' · generated ' + esc(gen) : ''}</div>
<div class="disclaimer">${esc(report.disclaimer)}</div>
<h2>Summary</h2>
${summaryHtml}
<h2>Node Analysis (${report.nodeRows.length} nodes)</h2>
<table><thead><tr><th>Ref</th><th>Elev (ft)</th><th>K</th><th>P (psi)</th><th>Q (gpm)</th></tr></thead>
<tbody>${nodeRowsHtml || '<tr><td colspan="5" class="muted">No nodes.</td></tr>'}</tbody></table>
<h2>Pipe Data (${report.pipeRows.length} pipes)</h2>
<table><thead><tr><th>Ref</th><th>From → To</th><th>Dia (in)</th><th>Len + Le (ft)</th><th>C</th><th>Flow (gpm)</th><th>Vel (fps)</th><th>Loss (psi)</th></tr></thead>
<tbody>${pipeRowsHtml || '<tr><td colspan="8" class="muted">No pipes.</td></tr>'}</tbody></table>
</body></html>`;
}
