import fs from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

const ROOT = path.resolve(import.meta.dirname, '..');

describe('SAM31 workbench browser smoke script', () => {
  it('publishes a bounded Playwright smoke for the saved-evidence replay path', () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
    expect(pkg.scripts['smoke:sam31-workbench']).toBe('node scripts/smoke-sam31-workbench.mjs');
    expect(pkg.devDependencies.playwright).toBe('^1.60.0');

    const script = fs.readFileSync(path.join(ROOT, 'scripts/smoke-sam31-workbench.mjs'), 'utf8');
    expect(script).toContain('playwright');
    expect(script).toContain('output/playwright');
    expect(script).toContain('/api/auth/login');
    expect(script).toContain('/pdf-boundary-decision');
    expect(script).toContain('/sam31-visual-audit/results');
    expect(script).toContain('SAM31 perception summary');
    expect(script).toContain('SAM31 HaloFire application contract');
    expect(script).toContain('openclaw.sam31.application_contract.halo_fire.v1');
    expect(script).toContain('sleeve_or_firestop_candidate_review');
    expect(script).toContain('acceptable_human_updates');
    expect(script).toContain('Replace temporary SAM31 values');
    expect(script).toContain('semantic_label');
    expect(script).toContain('polygon');
    expect(script).toContain('bbox');
    expect(script).toContain('object_hypothesis');
    expect(script).toContain('vector_overlay');
    expect(script).toContain('model_3d_candidate');
    expect(script).toContain('source_ref');
    expect(script).toContain('confidence');
    expect(script).toContain('data-sam31-replacement-action-field');
    expect(script).toContain('data-sam31-bridge-smoke-evidence-id');
    expect(script).toContain('runSam31BridgeSmokeArtifact');
    expect(script).toContain('/openclaw/sam31/smoke-artifact');
    expect(script).toContain('sam31BridgeSmokeStatus');
    expect(script).toContain('openclaw_sam31_bridge_smoke_artifact');
    expect(script).toContain('createSam31BridgeApp');
    expect(script).toContain('startSam31Bridge');
    expect(script).toContain('OPENCLAW_BRIDGE_URL: bridgeBaseUrl');
    expect(script).toContain('/openclaw/sam31/extrapolation-artifact');
    expect(script).toContain('SAM31 1881 bid truth');
    expect(script).toContain('head_count 1420');
    expect(script).toContain('SAM31 missing evidence rows');
    expect(script).toContain('HALOFIRE_1881_ROOM_BOUNDARY_EMPLOYEE_REVIEW_MISSING');
    expect(script).toContain('HALOFIRE_1881_PROFESSIONAL_AHJ_APPROVAL_MISSING');
    expect(script).toContain('Download SAM31 tool contract');
    expect(script).toContain('openclaw-sam31-tool-contract');
    expect(script).toContain('openclaw.sam31_llm_extrapolation_tool_contract_packet.v1');
    expect(script).toContain('halofire-api-local-contract');
    expect(script).toContain('requiredSectioningPipelineStages');
    expect(script).toContain('sectioning_pipeline_contract');
    expect(script).toContain('openclaw.sam31.sectioning_pipeline_contract.v1');
    expect(script).toContain('sam31_sectioning');
    expect(script).toContain('llm_object_identification');
    expect(script).toContain('vector_overlay_generation');
    expect(script).toContain('model_3d_candidate_generation');
    expect(script).toContain('product_review_queue');
    expect(script).toContain('cross_product_handoff_rows');
    expect(script).toContain('Download SAM31 sectioning pipeline contract');
    expect(script).toContain('sam31-sectioning-pipeline-contract');
    expect(script).toContain('openclaw.sam31.sectioning_pipeline_contract_packet.v1');
    expect(script).toContain('sectioningContractPacket');
    expect(script).toContain('Save SAM31 sectioning contract review');
    expect(script).toContain('openclaw_sam31_sectioning_pipeline_contract_review');
    expect(script).toContain('sectioningContractReview');
    expect(script).toContain('sam31_sectioning_contract_reviews_recorded');
    expect(script).toContain('Saved SAM31 sectioning contract review evidence detail');
    expect(script).toContain('Download SAM31 sectioning downstream resolver packet');
    expect(script).toContain('Save SAM31 sectioning downstream resolver packet');
    expect(script).toContain('halofire_sam31_sectioning_downstream_resolver_packet');
    expect(script).toContain('sam31_sectioning_downstream_resolver_packets_recorded');
    expect(script).toContain('sectioningDownstreamResolverPacket');
    expect(script).toContain('Download SAM31 sectioning sprinkler review adapter');
    expect(script).toContain('Save SAM31 sectioning sprinkler review adapter');
    expect(script).toContain('halofire_sam31_sectioning_sprinkler_review_adapter');
    expect(script).toContain('sam31_sectioning_sprinkler_review_adapters_recorded');
    expect(script).toContain('sectioningSprinklerReviewAdapterPacket');
    expect(script).toContain('latest_halofire_sam31_sectioning_sprinkler_review_adapter');
    expect(script).toContain('source_halofire_sam31_sectioning_downstream_resolver_packet_evidence_id');
    expect(script).toContain('source_halofire_sam31_sectioning_sprinkler_review_adapter_evidence_id');
    expect(script).toContain('SAM31 sectioning adapter source evidence');
    expect(script).toContain('Download SAM31 vector/model artifact packet');
    expect(script).toContain('Record SAM31 vector/model artifacts');
    expect(script).toContain('openclaw.sam31_vector_model_artifact_packet.v1');
    expect(script).toContain('sam31-vector-model-artifacts');
    expect(script).toContain('sam31_vector_model_artifacts_recorded 1');
    expect(script).toContain('latest_openclaw_sam31_vector_model_artifact');
    expect(script).toContain('Download SAM31 queue item');
    expect(script).toContain('sam31-product-review-queue-item');
    expect(script).toContain('OpenClaw SAM31 consumer queue smoke');
    expect(script).toContain('Run LandScout/NameForge SAM31 queue smoke');
    expect(script).toContain('data-sam31-consumer-smoke-evidence-id');
    expect(script).toContain('data-sam31-consumer-smoke-packet-evidence-id');
    expect(script).toContain('sam31ConsumerSmokeStatus');
    expect(script).toContain('openclaw.sam31.consumer_smoke_artifact.v1');
    expect(script).not.toContain("waitForSelector('text=openclaw_sam31_consumer_smoke_artifact evidence'");
    expect(script.indexOf("waitForSelector('text=Latest consumer smoke'")).toBeLessThan(
      script.indexOf("waitForSelector('text=posted_consumer_count'"),
    );
    expect(script).toContain('posted_consumer_count');
    expect(script).toContain('blocked_consumer_count');
    expect(script).toContain('posted_consumer_count 2');
    expect(script).toContain('blocked_consumer_count 0');
    expect(script).toContain('consumerSmokeArtifact.posted_consumer_count !== 2');
    expect(script).toContain('consumerSmokeArtifact.blocked_consumer_count !== 0');
    expect(script).toContain('accepted_queue_id');
    expect(script).toContain('persisted_review_packet_ref');
    expect(script).toContain('result.accepted_queue_id');
    expect(script).toContain('result.persisted_review_packet_ref');
    expect(script).toContain('consumer_review_tasks');
    expect(script).toContain('openclaw.sam31.consumer_review_task.v1');
    expect(script).toContain('required_source_provenance_fields');
    expect(script).toContain('source_openclaw_sam31_vector_model_artifact_evidence_id');
    expect(script).toContain('source_halofire_sam31_sectioning_sprinkler_review_adapter_evidence_id');
    expect(script).toContain('Open product-owner replacement intake');
    expect(script).toContain('data-sam31-product-owner-replacement-intake-evidence-id');
    expect(script).toContain('Opened product_owner_replacement_intake evidence');
    expect(script).toContain('openclaw.sam31.consumer_review_task_decision.v1');
    expect(script).toContain('openclaw_sam31_consumer_review');
    expect(script).toContain('requires_product_review');
    expect(script).toContain('task.accepted_queue_id');
    expect(script).toContain('task.persisted_review_packet_ref');
    expect(script).toContain('Save SAM31 consumer review decision');
    expect(script).toContain('sam31ConsumerReviewStatus');
    expect(script).toContain('consumerReview.accepted_queue_id');
    expect(script).toContain('Download SAM31 consumer review decision');
    expect(script).toContain('sam31-consumer-review-decision');
    expect(script).toContain('openclaw.sam31.consumer_review_decision_packet.v1');
    expect(script).toContain('consumerReviewPacket.accepted_queue_id');
    expect(script).toContain('sam31ConsumerReview=unresolved');
    expect(script).toContain('openclaw.sam31.consumer_smoke_artifact.v1');
    expect(script).toContain('sam31-consumer-smoke-artifact');
    expect(script).toContain('consumer_result');
    expect(script).toContain('localBridgeExtrapolationEvidenceId');
    expect(script).toContain('/sam31-replacements');
    expect(script).toContain('Save employee replacements');
    expect(script).toContain('sam31EmployeeReplacementValues');
    expect(script).toContain('sam31ReplacementStatus');
    expect(script).toContain('sam31_replacements_recorded');
    expect(script).toContain('Run replay bid');
    expect(script).toContain('room_boundary_replay_bid_artifact');
    expect(script).toContain('source_sam31_replacement_evidence_id');
    expect(script).toContain('sam31_employee_replacement');
    expect(script).toContain('employee adjusted corridor');
    expect(script).toContain('employee_adjusted_extruded_polygon');
    expect(script).toContain('best_guess_until_employee_replaced');
    expect(script).toContain('Download full SAM31 packet');
    expect(script).toContain('no_claims_cleared');
    expect(script).toContain('Next action: Upload signed manufacturer model approval');
    expect(script).toContain('Upload signed professional review');
    expect(script).toContain('Upload signed AHJ approval');
    expect(script).toContain('Upload signed AutoSprink/equivalent export');
    expect(script).toContain('disabledManufacturerGate');
    expect(script).toContain('catalogApprovalTargetGate');
    expect(script).toContain('catalog-approval-professional-review-packet');
    expect(script).toContain('catalog-approval-autosprink-packet');
    expect(script).toContain('halofire.catalog_approval_resolver_packet.v1');
    expect(script).toContain('Download selected approval packet');
    expect(script).toContain('catalog_approval_packet_ready');
    expect(script).toContain('catalogApproval=ready');
    expect(script).toContain('evidenceType=ahj_approval');
    expect(script).toContain('AHJ_APPROVAL_MISSING');
    expect(script).toContain('Ready approval packets');
    expect(script).toContain('ready_for_signed_evidence_upload');
  });
});
