import fs from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

const ROOT = path.resolve(import.meta.dirname, '..');

describe('SAM31 workbench browser smoke script', () => {
  it('publishes a bounded Playwright smoke for the saved-evidence replay path', () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
    expect(pkg.scripts['smoke:sam31-workbench']).toBe('node scripts/smoke-sam31-workbench.mjs');
    expect(pkg.devDependencies.playwright).toBe('^1.60.0');

    const script = fs.readFileSync(path.join(ROOT, 'scripts/smoke-sam31-workbench.mjs'), 'utf8');
    expect(script).toContain('playwright');
    expect(script).toContain('output/playwright');
    expect(script).toContain('/api/auth/login');
    expect(script).toContain('/pdf-boundary-decision');
    expect(script).toContain('/sam31-visual-audit/results');
    expect(script).toContain('SAM31 perception summary');
    expect(script).toContain('SAM31 HaloFire application contract');
    expect(script).toContain('openclaw.sam31.application_contract.halo_fire.v1');
    expect(script).toContain('sleeve_or_firestop_candidate_review');
    expect(script).toContain('acceptable_human_updates');
    expect(script).toContain('Replace temporary SAM31 values');
    expect(script).toContain('semantic_label');
    expect(script).toContain('polygon');
    expect(script).toContain('bbox');
    expect(script).toContain('object_hypothesis');
    expect(script).toContain('vector_overlay');
    expect(script).toContain('model_3d_candidate');
    expect(script).toContain('source_ref');
    expect(script).toContain('confidence');
    expect(script).toContain('data-sam31-replacement-action-field');
    expect(script).toContain('data-sam31-bridge-smoke-evidence-id');
    expect(script).toContain('runSam31BridgeSmokeArtifact');
    expect(script).toContain('/openclaw/sam31/smoke-artifact');
    expect(script).toContain('sam31BridgeSmokeStatus');
    expect(script).toContain('openclaw_sam31_bridge_smoke_artifact');
    expect(script).toContain('createSam31BridgeApp');
    expect(script).toContain('startSam31Bridge');
    expect(script).toContain('OPENCLAW_BRIDGE_URL: bridgeBaseUrl');
    expect(script).toContain('/openclaw/sam31/extrapolation-artifact');
    expect(script).toContain('SAM31 1881 bid truth');
    expect(script).toContain('head_count 1420');
    expect(script).toContain('SAM31 missing evidence rows');
    expect(script).toContain('HALOFIRE_1881_ROOM_BOUNDARY_EMPLOYEE_REVIEW_MISSING');
    expect(script).toContain('HALOFIRE_1881_PROFESSIONAL_AHJ_APPROVAL_MISSING');
    expect(script).toContain('Download SAM31 queue item');
    expect(script).toContain('sam31-product-review-queue-item');
    expect(script).toContain('OpenClaw SAM31 consumer queue smoke');
    expect(script).toContain('Run LandScout/NameForge SAM31 queue smoke');
    expect(script).toContain('data-sam31-consumer-smoke-evidence-id');
    expect(script).toContain('data-sam31-consumer-smoke-packet-evidence-id');
    expect(script).toContain('sam31ConsumerSmokeStatus');
    expect(script).toContain('openclaw_sam31_consumer_smoke_artifact');
    expect(script).toContain('posted_consumer_count');
    expect(script).toContain('blocked_consumer_count');
    expect(script).toContain('posted_consumer_count 2');
    expect(script).toContain('blocked_consumer_count 0');
    expect(script).toContain('consumerSmokeArtifact.posted_consumer_count !== 2');
    expect(script).toContain('consumerSmokeArtifact.blocked_consumer_count !== 0');
    expect(script).toContain('accepted_queue_id');
    expect(script).toContain('persisted_review_packet_ref');
    expect(script).toContain('result.accepted_queue_id');
    expect(script).toContain('result.persisted_review_packet_ref');
    expect(script).toContain('consumer_review_tasks');
    expect(script).toContain('openclaw.sam31.consumer_review_task.v1');
    expect(script).toContain('requires_product_review');
    expect(script).toContain('task.accepted_queue_id');
    expect(script).toContain('task.persisted_review_packet_ref');
    expect(script).toContain('openclaw.sam31.consumer_smoke_artifact.v1');
    expect(script).toContain('sam31-consumer-smoke-artifact');
    expect(script).toContain('consumer_result');
    expect(script).toContain('localBridgeExtrapolationEvidenceId');
    expect(script).toContain('/sam31-replacements');
    expect(script).toContain('Save employee replacements');
    expect(script).toContain('sam31EmployeeReplacementValues');
    expect(script).toContain('sam31ReplacementStatus');
    expect(script).toContain('sam31_replacements_recorded');
    expect(script).toContain('Run replay bid');
    expect(script).toContain('room_boundary_replay_bid_artifact');
    expect(script).toContain('source_sam31_replacement_evidence_id');
    expect(script).toContain('sam31_employee_replacement');
    expect(script).toContain('employee adjusted corridor');
    expect(script).toContain('employee_adjusted_extruded_polygon');
    expect(script).toContain('best_guess_until_employee_replaced');
    expect(script).toContain('Download full SAM31 packet');
    expect(script).toContain('no_claims_cleared');
  });
});
