// Auto-generated by scripts/author_from_manifest.py (Phase D.3).
// Source: data/phase_d_manifest.json (sku_intent='agf-1011-inspector-test').
// Do not hand-edit — regenerate from the manifest.
//
// @part agf_1011_inspector_test
// @kind device
// @category trim.inspector.test
// @display-name "AGF 1011 Inspector's Test & Drain Valve 1\""
// @mfg agf_manufacturing
// @mfg-pn 1011
// @listing UL
// @price-usd 145.00
// @install-minutes 25
// @crew journeyman
// @param size_in number default=1 label="Size" unit="in"
// @port inlet position=[0,0,0] direction=[0,0,-1] style=NPT_threaded size_in=1 role=run_a

size_in = 1.0;

function od_mm(nps) =
    nps ==   1  ? 33.4 :
    nps == 1.25 ? 42.2 :
    nps == 1.5  ? 48.3 :
    nps ==   2  ? 60.3 : 33.4;

od = od_mm(size_in);
box_w = 100;
box_h = 70;
box_d = 45;

union() {
    // Enclosure
    translate([0, box_h/2 + od/2, 0])
        cube([box_w, box_h, box_d], center = true);
    // Pipe saddle stub
    rotate([0, 90, 0])
        cylinder(h = od * 2.2, d = od * 1.1, center = true, $fn = 32);
    // Conduit nipple
    translate([0, box_h + od/2, 0])
        cylinder(h = 20, d = 20, center = true, $fn = 16);
}
