import { describe, expect, it } from 'vitest';
import { buildRoomCad } from '../src/engine/cad-model.js';
import { analyzeConnectivity, repairConnectivity } from '../src/engine/branch-connect.js';

const rect = (w, h) => [[0, 0], [w, 0], [w, h], [0, h]];
const model = (solids) => ({ solids });
const pipe = (from, to, diameterIn = 1.25, extra = {}) => ({ kind: 'pipe', from, to, diameterIn, ...extra });
const head = (position, name) => ({ kind: 'head', position, name });

// A minimal fully-connected single-branch system:
//   riser (floor->branch) -> branch line along X -> 3 drops -> 3 heads.
function tinySystem() {
  const z = 12, hz = 9.5;
  const solids = [
    pipe([0, 0, 0], [0, 0, z], 2.0, { name: 'riser' }),   // riser to branch elev
    pipe([0, 0, z], [30, 0, z], 1.5, { name: 'branch' }), // branch line along X
  ];
  for (let i = 1; i <= 3; i += 1) {
    const x = i * 8;
    solids.push(pipe([x, 0, z], [x, 0, hz], 1.0, { name: `drop${i}` }));
    solids.push(head([x, 0, hz], `head${i}`));
  }
  return model(solids);
}

describe('branch-connect — connectivity analysis', () => {
  it('reports every head connected on a fully-wired tiny system', () => {
    const a = analyzeConnectivity(tinySystem());
    expect(a.totalHeads).toBe(3);
    expect(a.headsConnected).toBe(3);
    expect(a.orphanHeads).toBe(0);
    expect(a.branchCount).toBe(1);
    expect(a.riserCount).toBe(1);
    expect(a.sourcedComponentCount).toBe(1);
    expect(a.componentCount).toBe(1);
  });

  it('detects an ORPHAN branch that never ties into the riser', () => {
    const sys = tinySystem();
    // add a second branch + heads that float, NOT connected to the riser network
    const z = 12, hz = 9.5;
    sys.solids.push(pipe([0, 40, z], [30, 40, z], 1.5, { name: 'orphan-branch' }));
    for (let i = 1; i <= 4; i += 1) {
      const x = i * 7;
      sys.solids.push(pipe([x, 40, z], [x, 40, hz], 1.0, { name: `orphan-drop${i}` }));
      sys.solids.push(head([x, 40, hz], `orphan-head${i}`));
    }
    const a = analyzeConnectivity(sys);
    expect(a.totalHeads).toBe(7);
    expect(a.headsConnected).toBe(3);   // only the original branch reaches the riser
    expect(a.orphanHeads).toBe(4);      // the floating branch's heads are orphaned
    expect(a.orphanHeadNames).toContain('orphan-head1');
    expect(a.componentCount).toBe(2);
    expect(a.sourcedComponentCount).toBe(1);
  });

  it('counts heads attached via interior taps (drop taps a branch interior)', () => {
    // branch is ONE long segment; the drop taps its INTERIOR, not an endpoint.
    const z = 12, hz = 9.5;
    const a = analyzeConnectivity(model([
      pipe([0, 0, 0], [0, 0, z], 2.0, { name: 'riser' }),
      pipe([0, 0, z], [40, 0, z], 1.5, { name: 'branch' }),
      pipe([20, 0, z], [20, 0, hz], 1.0, { name: 'interior-drop' }), // taps interior
      head([20, 0, hz], 'mid-head'),
    ]));
    expect(a.headsConnected).toBe(1);
    expect(a.orphanHeads).toBe(0);
  });
});

describe('branch-connect — repair', () => {
  it('connects an orphan branch by synthesizing a tie-in + tee, dropping orphans to 0', () => {
    const sys = tinySystem();
    const z = 12, hz = 9.5;
    sys.solids.push(pipe([0, 40, z], [30, 40, z], 1.5, { name: 'orphan-branch' }));
    for (let i = 1; i <= 4; i += 1) {
      const x = i * 7;
      sys.solids.push(pipe([x, 40, z], [x, 40, hz], 1.0, { name: `orphan-drop${i}` }));
      sys.solids.push(head([x, 40, hz], `orphan-head${i}`));
    }
    const before = analyzeConnectivity(sys);
    expect(before.orphanHeads).toBe(4);

    const { added, analysisAfter } = repairConnectivity(sys);
    expect(added.length).toBeGreaterThan(0);
    // a tie-in pipe + a tee fitting were synthesized
    expect(added.some((s) => s.kind === 'pipe' && s.autoGenerated)).toBe(true);
    expect(added.some((s) => s.kind === 'component' && s.componentKey === 'fitting_tee')).toBe(true);
    // every head now traces back to the riser
    expect(analysisAfter.orphanHeads).toBe(0);
    expect(analysisAfter.headsConnected).toBe(7);
    expect(analysisAfter.sourcedComponentCount).toBe(analysisAfter.componentCount);
  });

  it('is idempotent: a fully-connected model gets zero additions', () => {
    const sys = tinySystem();
    const { added, analysisAfter } = repairConnectivity(sys);
    expect(added.length).toBe(0);
    expect(analysisAfter.orphanHeads).toBe(0);
  });

  it('connects MULTIPLE orphan branches (re-floods between ties)', () => {
    const sys = tinySystem();
    const z = 12, hz = 9.5;
    for (const yOff of [40, 80]) {
      sys.solids.push(pipe([0, yOff, z], [30, yOff, z], 1.5, { name: `orphan-branch-${yOff}` }));
      for (let i = 1; i <= 3; i += 1) {
        const x = i * 8;
        sys.solids.push(pipe([x, yOff, z], [x, yOff, hz], 1.0, { name: `od-${yOff}-${i}` }));
        sys.solids.push(head([x, yOff, hz], `oh-${yOff}-${i}`));
      }
    }
    const before = analyzeConnectivity(sys);
    expect(before.orphanHeads).toBe(6);
    const { analysisAfter } = repairConnectivity(sys);
    expect(analysisAfter.orphanHeads).toBe(0);
    expect(analysisAfter.totalHeads).toBe(9);
  });
});

describe('branch-connect — golden generated model is already connected', () => {
  const room = { name: 'Bay', polygon: rect(80, 60), hazard: 'ordinary', ceilingHeightFt: 16 };
  const cad = buildRoomCad(room);
  const a = analyzeConnectivity(cad);

  it('every head on the generated buildRoomCad model traces back to the riser', () => {
    expect(a.totalHeads).toBeGreaterThan(0);
    expect(a.orphanHeads).toBe(0);
    expect(a.headsConnected).toBe(a.totalHeads);
    expect(a.riserCount).toBeGreaterThanOrEqual(1);
  });

  it('reports a sensible branch-line count (one per occupied grid row)', () => {
    expect(a.branchCount).toBeGreaterThan(1);
    expect(a.branchCount).toBeLessThan(a.totalHeads); // fewer branches than heads
  });

  it('repair is a no-op on the already-connected generated model', () => {
    const cad2 = buildRoomCad(room);
    const { added } = repairConnectivity(cad2);
    expect(added.length).toBe(0);
  });
});

describe('branch-connect — guards', () => {
  it('handles empty / pipe-less models without throwing', () => {
    expect(analyzeConnectivity(model([])).orphanHeads).toBe(0);
    expect(analyzeConnectivity(model([head([0, 0, 0], 'h')])).orphanHeads).toBe(1);
    const r = repairConnectivity(model([]));
    expect(r.added.length).toBe(0);
  });
});
