import fs from 'node:fs';
import { describe, expect, it } from 'vitest';

const proof = new URL('../src/data/proofs/new-hope-truss-clearance/', import.meta.url);
const read = (name) => fs.readFileSync(new URL(name, proof), 'utf8');

describe('New Hope PDF-bound visual proof', () => {
  it('keeps the actual structural and approved PDF renders beneath the overlays', () => {
    const html = read('index.html');
    expect(html).toContain('s102-roof-framing-underlay.png');
    expect(html).toContain('approved-ridge-branch-underlay.png');
    expect(html).toContain('approved-dry-pipe-note.png');
    expect(html).toContain('approved-fp20-full-underlay.png');
    expect(html).toContain('architectural-a102-rcp.png');
    expect(html).toContain('architectural-a103-roof-plan.png');
    expect(html).toContain('architectural-a201-elevations.png');
    expect(html).toContain('architectural-a301-sections.png');
    for (const image of ['s102-roof-framing-underlay.png', 'approved-ridge-branch-underlay.png', 'approved-dry-pipe-note.png', 'approved-fp20-full-underlay.png', 'approved-fp20-pipe-size-overlay.png', 'architectural-a102-rcp.png', 'architectural-a103-roof-plan.png', 'architectural-a201-elevations.png', 'architectural-a301-sections.png']) expect(fs.statSync(new URL(image, proof)).size).toBeGreaterThan(30_000);
  });

  it('states the missing pipe-layout facts instead of presenting a connector as a design', () => {
    const html = read('index.html');
    expect(html).toContain('WHOLE-SHEET PIPE DIRECTION + ALL 12 ARM-OVERS BOUND');
    expect(html).toContain('primaryPipeVectorExtractionReady=false');
    expect(html).toContain('wholeSystemVectorExtractionReady=false');
    expect(html).toContain('primaryPipeSizeAssignmentReady=false');
    expect(html).toContain('fieldDrainRouteResolved=false');
    expect(html).toContain('properPipeLayoutReady=false');
    expect(html).toContain('endpointElevationsReady=false');
    expect(html).toContain('architecturalSourceRegistrationReady=false');
    expect(html).toContain('architecturalVerticalControlReady=false');
    expect(html).toContain('pipeCenterlineOffsetReady=false');
    expect(html).toContain('longBranchSourceTopologyReady=false');
    expect(html).toContain('longBranchLowPointBindingReady=false');
    expect(html).toContain('longBranchGradeDirectionReady=false');
    expect(html).toContain('longBranchRelativeGradeProfilesReady=false');
    expect(html).toContain('sideBranchSourceTopologyReady=false');
    expect(html).toContain('sideBranchLowPointBindingReady=false');
    expect(html).toContain('sideBranchLineGradeDirectionReady=false');
    expect(html).toContain('sideBranchRelativeGradeProfilesReady=false');
    expect(html).toContain('sideBranchArmOverDrainageReady=false');
    expect(html).toContain('crossMainSourceTopologyReady=false');
    expect(html).toContain('crossMainHighPointBindingReady=false');
    expect(html).toContain('crossMainLowPointBindingReady=false');
    expect(html).toContain('crossMainRiserReturnReady=false');
    expect(html).toContain('crossMainGradeDirectionReady=false');
    expect(html).toContain('crossMainRelativeGradeProfilesReady=false');
    expect(html).toContain('upperHighPointAbsoluteZReady=false');
    expect(html).toContain('cmkLineBindingReady=false');
    expect(html).toContain('cmkHighPointBindingReady=false');
    expect(html).toContain('cmkHighPointAbsoluteZReady=false');
    expect(html).toContain('centralBranchSourceTopologyReady=false');
    expect(html).toContain('centralBranchFabricationLineBindingReady=false');
    expect(html).toContain('centralBranchSeparatedCrossingReady=false');
    expect(html).toContain('centralBranchGeneratedGradeDirectionReady=false');
    expect(html).toContain('centralBranchRelativeGradeProfilesReady=false');
    expect(html).toContain('centralLoopDirectionReady=false');
    expect(html).toContain('selectedLoopHighPointAbsoluteZReady=false');
    expect(html).toContain('centralBranchArmOverDrainageReady=false');
    expect(html).toContain('boundedRidgeBranchGradeDirectionReady=false');
    expect(html).toContain('boundedRidgeBranchDrainCatchmentReady=false');
    expect(html).toContain('boundedDeflectorGradeEnvelopeReady=false');
    expect(html).toContain('exactDeflectorElevationsReady=false');
    expect(html).toContain('exactPipeCenterlineZReady=false');
    expect(html).toContain('wholeFp20GradeDirectionReady=false');
    expect(html).toContain('approvedRemoteAreaSetReady=false');
    expect(html).toContain('approvedRemoteAreaHydraulicFlowReady=false');
    expect(html).toContain('route21ExplicitPlanPathReady=false');
    expect(html).toContain('route22ExplicitPlanPathReady=false');
    expect(html).toContain('route23ExplicitPlanPathReady=false');
  });

  it('loads the sealed calibration and generates the S102 overlay from data', () => {
    const script = read('proof.js');
    expect(script).toContain('../../new-hope-truss-clearance-calibration.json');
    expect(script).toContain('../../new-hope-approved-fp20-pipe-vectors.json');
    expect(script).toContain('../../new-hope-approved-fp20-plan-graph.json');
    expect(script).toContain('../../new-hope-approved-fp20-operational-annotations.json');
    expect(script).toContain('../../new-hope-approved-fp20-hydraulic-route-2-1.json');
    expect(script).toContain('../../new-hope-approved-fp20-hydraulic-route-2-2.json');
    expect(script).toContain('../../new-hope-approved-fp20-hydraulic-route-2-3.json');
    expect(script).toContain('../../new-hope-pitched-holdout-source.json');
    expect(script).toContain('evaluateApprovedFp20ArchitecturalVerticalControls');
    expect(script).toContain('../../new-hope-attic-specific-application-source.json');
    expect(script).toContain('../../new-hope-attic-specific-application-calibration.json');
    expect(script).toContain('../../new-hope-pitched-holdout-answer-evidence.json');
    expect(script).toContain('evaluateNewHopeRidgeBranchGradeEnvelope');
    expect(script).toContain('evaluateNewHopeLongBranchDrainage');
    expect(script).toContain('evaluateNewHopeSideBranchDrainage');
    expect(script).toContain('evaluateNewHopeCrossMainDrainage');
    expect(script).toContain('evaluateNewHopeCentralBranchDrainage');
    expect(script).toContain('evaluateNewHopeArmOverDrainage');
    expect(script).toContain('calibration.trussLattice.centerlines');
    expect(script).toContain('calibration.branch.nodes');
    expect(script).toContain('pipeVectors.pipeSegments');
    expect(script).toContain('pipeVectors.sprinklers');
    expect(script).toContain('pipeVectors.pipeSizeAnnotations');
    expect(script).toContain('buildApprovedFp20PlanGraph');
    expect(script).toContain('evaluateApprovedFp20PipeVectors');
    expect(script).toContain('evaluateApprovedFp20GovernedSkeleton');
    expect(script).toContain('canonicalizeApprovedFp20Topology');
    expect(script).toContain('bindApprovedFp20HydraulicRouteSet');
    expect(script).toContain("dataset.proofReady = 'true'");
    expect(script).toContain('dataset.architecturalSourceRegistrationReady = String(architecturalValidation.sourceRegistrationReady)');
    expect(script).toContain('dataset.architecturalVerticalControlReady = String(architecturalVerticalControlReady)');
    expect(script).toContain('dataset.pipeCenterlineOffsetReady = String(pipeCenterlineOffsetReady)');
    expect(script).toContain('dataset.longBranchSourceTopologyReady = String(longBranchDrainage.longBranchSourceTopologyReady)');
    expect(script).toContain('dataset.longBranchLowPointBindingReady = String(longBranchDrainage.longBranchLowPointBindingReady)');
    expect(script).toContain('dataset.longBranchGradeDirectionReady = String(longBranchDrainage.longBranchGradeDirectionReady)');
    expect(script).toContain('dataset.longBranchRelativeGradeProfilesReady = String(longBranchDrainage.longBranchRelativeGradeProfilesReady)');
    expect(script).toContain('dataset.sideBranchSourceTopologyReady = String(sideBranchDrainage.sideBranchSourceTopologyReady)');
    expect(script).toContain('dataset.sideBranchLowPointBindingReady = String(sideBranchDrainage.sideBranchLowPointBindingReady)');
    expect(script).toContain('dataset.sideBranchLineGradeDirectionReady = String(sideBranchDrainage.sideBranchLineGradeDirectionReady)');
    expect(script).toContain('dataset.sideBranchRelativeGradeProfilesReady = String(sideBranchDrainage.sideBranchRelativeGradeProfilesReady)');
    expect(script).toContain('dataset.sideBranchArmOverDrainageReady = String(armOverDrainage.sideBranchArmOverDrainageReady)');
    expect(script).toContain('dataset.crossMainSourceTopologyReady = String(crossMainDrainage.crossMainSourceTopologyReady)');
    expect(script).toContain('dataset.crossMainHighPointBindingReady = String(crossMainDrainage.crossMainHighPointBindingReady)');
    expect(script).toContain('dataset.crossMainLowPointBindingReady = String(crossMainDrainage.crossMainLowPointBindingReady)');
    expect(script).toContain('dataset.crossMainRiserReturnReady = String(crossMainDrainage.crossMainRiserReturnReady)');
    expect(script).toContain('dataset.crossMainGradeDirectionReady = String(crossMainDrainage.crossMainGradeDirectionReady)');
    expect(script).toContain('dataset.crossMainRelativeGradeProfilesReady = String(crossMainDrainage.crossMainRelativeGradeProfilesReady)');
    expect(script).toContain('dataset.upperHighPointAbsoluteZReady = String(crossMainDrainage.upperHighPointAbsoluteZReady)');
    expect(script).toContain('dataset.cmkLineBindingReady = String(crossMainDrainage.cmkLineBindingReady)');
    expect(script).toContain('dataset.cmkHighPointBindingReady = String(crossMainDrainage.cmkHighPointBindingReady)');
    expect(script).toContain('dataset.cmkHighPointAbsoluteZReady = String(crossMainDrainage.cmkHighPointAbsoluteZReady)');
    expect(script).toContain('dataset.centralBranchSourceTopologyReady = String(centralBranchDrainage.centralBranchSourceTopologyReady)');
    expect(script).toContain('dataset.centralBranchFabricationLineBindingReady = String(centralBranchDrainage.centralBranchFabricationLineBindingReady)');
    expect(script).toContain('dataset.centralBranchSeparatedCrossingReady = String(centralBranchDrainage.centralBranchSeparatedCrossingReady)');
    expect(script).toContain('dataset.centralBranchGeneratedGradeDirectionReady = String(centralBranchDrainage.centralBranchGeneratedGradeDirectionReady)');
    expect(script).toContain('dataset.centralBranchRelativeGradeProfilesReady = String(centralBranchDrainage.centralBranchRelativeGradeProfilesReady)');
    expect(script).toContain('dataset.centralLoopDirectionReady = String(centralBranchDrainage.centralLoopDirectionReady)');
    expect(script).toContain('dataset.selectedLoopHighPointAbsoluteZReady = String(centralBranchDrainage.selectedLoopHighPointAbsoluteZReady)');
    expect(script).toContain('dataset.centralBranchArmOverDrainageReady = String(armOverDrainage.centralBranchArmOverDrainageReady)');
    expect(script).toContain('dataset.allTwelveArmOverDrainageReady = String(armOverDrainage.allTwelveArmOverDrainageReady)');
    expect(script).toContain('dataset.wholeFp20GradeDirectionReady = String(properPipeLayout.wholeFp20RelativeGradeDirectionReady)');
    expect(script).toContain('dataset.boundedRidgeBranchGradeDirectionReady = String(ridgeGrade.boundedBranchGradeDirectionReady)');
    expect(script).toContain('dataset.boundedRidgeBranchDrainCatchmentReady = String(ridgeGrade.boundedBranchDrainCatchmentReady)');
    expect(script).toContain('dataset.boundedDeflectorGradeEnvelopeReady = String(ridgeGrade.boundedDeflectorGradeEnvelopeReady)');
    expect(script).toContain('dataset.exactDeflectorElevationsReady = String(ridgeGrade.exactDeflectorElevationsReady)');
    expect(script).toContain('dataset.exactPipeCenterlineZReady = String(properPipeLayout.exactPipeCenterlineZReady)');
    expect(script).toContain('evaluateNewHopeSourceFeedFabrication');
    expect(script).toContain('dataset.sourceFeedPlanFabricationReady = String(properPipeLayout.sourceFeedPlanFabricationReady)');
    expect(script).toContain('dataset.sourceFeedOutletTransitionReady = String(properPipeLayout.sourceFeedOutletTransitionReady)');
    expect(script).toContain('dataset.sourceFeedOutletElevationReady = String(properPipeLayout.sourceFeedOutletElevationReady)');
    expect(script).toContain('dataset.sourceFeedInstalledGradeReady = String(properPipeLayout.sourceFeedInstalledGradeReady)');
    expect(script).toContain('bounded-grade-vector');
    expect(script).toContain('bounded-grade-profile');
    expect(script).toContain('long-branch-grade-vector');
    expect(script).toContain('long-branch-relative-profile');
    expect(script).toContain('side-branch-grade-vector');
    expect(script).toContain('side-branch-relative-profile');
    expect(script).toContain('cross-main-grade-vector');
    expect(script).toContain('cross-main-relative-profile');
    expect(script).toContain('central-branch-grade-vector');
    expect(script).toContain('central-branch-relative-profile');
    expect(script).toContain('arm-over-grade-vector');
    expect(script).toContain('arm-over-relative-profile');
    expect(script).toContain('dataset.pipeVectorStatus = vectorAcceptance.status');
    expect(script).toContain('dataset.primaryPipeSizeAssignmentReady = String(governedSkeleton.primaryPipeSizeAssignmentReady)');
    expect(script).toContain('dataset.primaryPipeRoleAssignmentReady = String(governedSkeleton.primaryPipeRoleAssignmentReady)');
    expect(script).toContain('dataset.wholeSystemVectorExtractionReady = String(governedSkeleton.wholeSystemVectorExtractionReady)');
    expect(script).toContain('dataset.properPipeLayoutReady = String(properPipeLayout.properPipeLayoutReady)');
    expect(script).toContain('dataset.branchGradeDirectionReady = String(properPipeLayout.wholeFp20RelativeGradeDirectionReady)');
    expect(script).toContain('dataset.endpointElevationsReady = String(properPipeLayout.exactPipeCenterlineZReady)');
    expect(script).toContain('dataset.route21HydraulicNodeBindingReady = String(hydraulicRoute21.route21HydraulicNodeBindingReady)');
    expect(script).toContain('dataset.route21ExplicitPlanPathReady = String(hydraulicRoute21.explicitPlanPathReady)');
    expect(script).toContain('dataset.route22ExplicitPlanPathReady = String(hydraulicRoute22.explicitPlanPathReady)');
    expect(script).toContain('dataset.route23ExplicitPlanPathReady = String(hydraulicRoute23.explicitPlanPathReady)');
    expect(script).toContain('dataset.approvedRemoteAreaSetReady = String(hydraulicRouteSet.approvedRemoteAreaSetReady)');
    expect(script).toContain("dataset.drainDestinationReady = 'false'");
    expect(script).toContain('evaluateProperPitchedPipeGraph');
    expect(script).toContain("dataset.pipeGraphStatus = properPipeLayout.properPipeLayoutReady ? 'passed' : 'blocked'");
    expect(script).toContain('properPipeLayout.acceptanceBlockers');
  });
});
