// Builds public/halofire-menubar.js from the scraped AutoSprink menu research.
// Source of truth: docs/research/autosprink-menus.json (scraped 2026-06-12,
// needs-verification). Re-run after re-scraping:
//   node scripts/build-menubar.mjs
import fs from 'node:fs';
import path from 'node:path';

const APP = path.resolve(import.meta.dirname, '..');
const RESEARCH = path.resolve(APP, '../../docs/research/autosprink-menus.json');
const OUT = path.resolve(APP, 'public/halofire-menubar.js');

const research = JSON.parse(fs.readFileSync(RESEARCH, 'utf-8'));

function slug(s) {
  return s.toLowerCase().replace(/['’]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

const menus = research.menus.map((m) => ({
  menu: m.menu,
  id: slug(m.menu),
  items: m.items.map((it) => {
    const item = { id: `${slug(m.menu)}.${slug(it.name)}`, name: it.name, desc: it.desc };
    if (it.shortcut) item.shortcut = it.shortcut;
    return item;
  }),
}));

const DATA = JSON.stringify(menus);
const PROVENANCE = research.provenance || 'scraped 2026-06-12, needs-verification';

const component = `/* HaloFire Studio — AutoSprink-parity menu bar (apple-glass).
 *
 * Self-contained: inject <script src="/public/halofire-menubar.js"></script>
 * then call window.HFMenuBar.mount(container, { actions }).
 *
 * - actions maps item ids ("file.save", "view.camera", "export") to callbacks.
 *   Items WITHOUT an action render grayed with tooltip
 *   "not yet wired — needs-verification" (flag-don't-gate doctrine).
 * - File > Export submenu (DXF/STEP/IFC/STL) calls actions.export(format).
 * - Keyboard: click or Alt+<underlined letter> opens a menu, Esc closes,
 *   arrows navigate, Enter/Space activates, Home/End jump.
 *
 * Menu structure provenance: ${PROVENANCE}
 * (official docs https://autosprink.com/help/1?v=latest — NOT AutoSprink
 * parity; every item needs human verification against the real app).
 *
 * GENERATED by apps/autosprink/scripts/build-menubar.mjs from
 * docs/research/autosprink-menus.json — edit the builder, not this file.
 */
(function () {
  'use strict';

  var PROVENANCE = ${JSON.stringify(PROVENANCE)};
  var STUB_TIP = 'not yet wired \\u2014 needs-verification';
  var EXPORT_FORMATS = ['DXF', 'STEP', 'IFC', 'STL'];
  var MENU_DATA = ${DATA};

  var STYLE_ID = 'hf-menubar-style';
  var CSS = [
    '.hf-menubar{position:relative;display:flex;align-items:center;gap:1px;padding:3px 6px;',
    'background:rgba(14,19,24,.78);backdrop-filter:blur(20px) saturate(150%);-webkit-backdrop-filter:blur(20px) saturate(150%);',
    'border:1px solid var(--hf-color-border,#2a323d);border-radius:10px;',
    "font-family:'Inter Variable',Inter,system-ui,sans-serif;font-size:12.5px;line-height:1.2;",
    'color:var(--hf-color-text-primary,#f0f4f8);user-select:none;flex-wrap:wrap;}',
    '.hf-menubar-top{position:relative;}',
    '.hf-menubar-btn{appearance:none;background:transparent;border:0;border-radius:6px;padding:5px 9px;',
    'color:inherit;font:inherit;cursor:pointer;white-space:nowrap;}',
    '.hf-menubar-btn:hover,.hf-menubar-btn:focus-visible{background:rgba(255,255,255,.07);outline:none;}',
    '.hf-menubar-btn[aria-expanded="true"]{background:rgba(240,168,104,.16);color:var(--hf-color-accent-text,#f4b87f);}',
    '.hf-menubar-btn u{text-decoration:underline;text-underline-offset:2px;}',
    '.hf-menu{position:absolute;top:calc(100% + 4px);left:0;z-index:4000;min-width:240px;max-width:340px;',
    'max-height:min(68vh,620px);overflow-y:auto;padding:5px;',
    'background:rgba(17,22,29,.92);backdrop-filter:blur(24px) saturate(150%);-webkit-backdrop-filter:blur(24px) saturate(150%);',
    'border:1px solid var(--hf-color-border-strong,#3a4654);border-radius:12px;',
    'box-shadow:0 18px 44px rgba(0,0,0,.55),0 2px 8px rgba(0,0,0,.4);}',
    '.hf-menu[hidden]{display:none;}',
    '.hf-menu-item{position:relative;display:flex;align-items:center;gap:8px;width:100%;text-align:left;',
    'appearance:none;background:transparent;border:0;border-radius:7px;padding:6px 9px;',
    'color:var(--hf-color-text-primary,#f0f4f8);font:inherit;cursor:pointer;}',
    '.hf-menu-item:hover,.hf-menu-item:focus-visible,.hf-menu-item.hf-active{background:rgba(240,168,104,.14);outline:none;}',
    '.hf-menu-item[aria-disabled="true"]{color:var(--hf-color-text-muted,#b8c1cb);opacity:.5;cursor:default;}',
    '.hf-menu-item[aria-disabled="true"]:hover{background:rgba(255,255,255,.04);}',
    '.hf-menu-item .hf-flag{margin-left:auto;font-size:9px;letter-spacing:.04em;color:var(--hf-color-warn,#fbbf24);opacity:.85;}',
    '.hf-menu-item .hf-sub-arrow{margin-left:auto;opacity:.7;font-size:10px;}',
    '.hf-menu-item .hf-shortcut{margin-left:auto;color:var(--hf-color-text-muted,#b8c1cb);font-size:11px;}',
    '.hf-submenu{position:fixed;z-index:4001;min-width:130px;padding:5px;',
    'background:rgba(17,22,29,.94);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px);',
    'border:1px solid var(--hf-color-border-strong,#3a4654);border-radius:10px;',
    'box-shadow:0 14px 34px rgba(0,0,0,.5);}',
    '.hf-submenu[hidden]{display:none;}',
    '.hf-menu-foot{padding:6px 9px 3px;border-top:1px solid var(--hf-color-border,#2a323d);margin-top:4px;',
    'font-size:9.5px;letter-spacing:.03em;color:var(--hf-color-text-muted,#b8c1cb);}'
  ].join('');

  function injectStyle() {
    if (document.getElementById(STYLE_ID)) return;
    var style = document.createElement('style');
    style.id = STYLE_ID;
    style.textContent = CSS;
    document.head.appendChild(style);
  }

  // Greedy unique Alt-mnemonic per menu: first letter of the menu name not yet
  // claimed; menus with no free letter get no mnemonic (honest, deterministic).
  function assignMnemonics(names) {
    var used = {};
    return names.map(function (name) {
      var letters = name.toUpperCase().replace(/[^A-Z]/g, '');
      for (var i = 0; i < letters.length; i++) {
        var ch = letters[i];
        if (!used[ch]) { used[ch] = true; return ch; }
      }
      return null;
    });
  }

  function mount(container, opts) {
    opts = opts || {};
    var actions = opts.actions || {};
    injectStyle();

    var state = { openMenu: null, openSub: null };
    var bar = document.createElement('nav');
    bar.className = 'hf-menubar';
    bar.setAttribute('role', 'menubar');
    bar.setAttribute('aria-label', 'Studio menu bar');

    var stats = { menus: MENU_DATA.length, items: 0, wired: 0, stubbed: 0 };
    var menuEls = [];
    var portals = []; // body-mounted flyouts, removed on unmount

    var mnemonics = assignMnemonics(MENU_DATA.map(function (m) { return m.menu; }));

    function closeAll() {
      if (state.openSub) { state.openSub.hidden = true; state.openSub = null; }
      if (state.openMenu) {
        state.openMenu.panel.hidden = true;
        state.openMenu.btn.setAttribute('aria-expanded', 'false');
        state.openMenu = null;
      }
    }

    function openMenu(entry, focusFirst) {
      if (state.openMenu === entry) return;
      closeAll();
      entry.panel.hidden = false;
      entry.btn.setAttribute('aria-expanded', 'true');
      state.openMenu = entry;
      if (focusFirst) {
        var first = entry.panel.querySelector('.hf-menu-item');
        if (first) first.focus();
      }
    }

    function itemAction(id) {
      var fn = actions[id];
      return typeof fn === 'function' ? fn : null;
    }

    function buildItem(item, menuPanel) {
      var el = document.createElement('button');
      el.type = 'button';
      el.className = 'hf-menu-item';
      el.setAttribute('role', 'menuitem');
      el.dataset.id = item.id;
      el.title = item.desc + ' [' + PROVENANCE + ']';
      var label = document.createElement('span');
      label.textContent = item.name;
      el.appendChild(label);
      stats.items++;

      var isExport = item.id === 'file.export';
      var fn = itemAction(item.id);

      if (isExport) {
        // File > Export submenu: DXF/STEP/IFC/STL -> actions.export(format)
        el.setAttribute('aria-haspopup', 'menu');
        el.setAttribute('aria-expanded', 'false');
        var arrow = document.createElement('span');
        arrow.className = 'hf-sub-arrow';
        arrow.textContent = '\\u25B8';
        el.appendChild(arrow);
        // PORTAL: the submenu lives on document.body — backdrop-filter on the
        // dropdown panel creates a containing block that would trap and clip a
        // position:fixed descendant inside the panel's overflow.
        var sub = document.createElement('div');
        sub.className = 'hf-submenu';
        sub.setAttribute('role', 'menu');
        sub.setAttribute('aria-label', item.name + ' submenu');
        sub.hidden = true;
        document.body.appendChild(sub);
        portals.push(sub);
        var exportFn = typeof actions.export === 'function' ? actions.export : null;
        EXPORT_FORMATS.forEach(function (fmt) {
          var fmtId = 'file.export.' + fmt.toLowerCase();
          var fmtFn = itemAction(fmtId) || (exportFn ? function () { return exportFn(fmt.toLowerCase()); } : null);
          var fEl = document.createElement('button');
          fEl.type = 'button';
          fEl.className = 'hf-menu-item';
          fEl.setAttribute('role', 'menuitem');
          fEl.dataset.id = fmtId;
          fEl.textContent = fmt;
          stats.items++;
          if (fmtFn) {
            stats.wired++;
            fEl.addEventListener('click', function (e) { e.stopPropagation(); closeAll(); fmtFn(); });
          } else {
            stats.stubbed++;
            fEl.setAttribute('aria-disabled', 'true');
            fEl.title = STUB_TIP;
            fEl.addEventListener('click', function (e) { e.stopPropagation(); });
          }
          sub.appendChild(fEl);
        });
        // fixed positioning so the flyout escapes the scrolling dropdown's
        // overflow clipping; flip to the left edge if it would overflow.
        var positionSub = function () {
          var r = el.getBoundingClientRect();
          sub.style.top = Math.max(4, Math.min(r.top - 6, window.innerHeight - sub.offsetHeight - 8)) + 'px';
          var left = r.right - 4;
          if (left + sub.offsetWidth > window.innerWidth - 8) left = r.left - sub.offsetWidth + 4;
          sub.style.left = Math.max(4, left) + 'px';
        };
        var toggleSub = function (show) {
          if (state.openSub && state.openSub !== sub) state.openSub.hidden = true;
          sub.hidden = !show;
          el.setAttribute('aria-expanded', String(show));
          state.openSub = show ? sub : null;
          if (show) positionSub();
        };
        // keep the fixed flyout glued to its parent item while the dropdown scrolls
        menuPanel.addEventListener('scroll', function () { if (!sub.hidden) positionSub(); });
        el.addEventListener('click', function (e) { e.stopPropagation(); toggleSub(sub.hidden); });
        el.addEventListener('keydown', function (e) {
          if (e.key === 'ArrowRight' || e.key === 'Enter' || e.key === ' ') {
            e.preventDefault(); e.stopPropagation();
            toggleSub(true);
            var first = sub.querySelector('.hf-menu-item');
            if (first) first.focus();
          }
        });
        // the portal is outside the bar, so it carries its own keyboard nav
        sub.addEventListener('keydown', function (e) {
          var items = Array.prototype.slice.call(sub.querySelectorAll('.hf-menu-item'));
          var cur = items.indexOf(document.activeElement);
          if (e.key === 'ArrowLeft' || e.key === 'Escape') {
            e.preventDefault(); e.stopPropagation(); toggleSub(false); el.focus();
          } else if (e.key === 'ArrowDown') {
            e.preventDefault(); items[(cur + 1) % items.length].focus();
          } else if (e.key === 'ArrowUp') {
            e.preventDefault(); items[(cur - 1 + items.length) % items.length].focus();
          }
        });
        // export parent counts as wired when any export path exists
        if (exportFn || EXPORT_FORMATS.some(function (f) { return itemAction('file.export.' + f.toLowerCase()); })) stats.wired++;
        else stats.stubbed++;
        return el;
      }

      if (item.shortcut) {
        var sc = document.createElement('span');
        sc.className = 'hf-shortcut';
        sc.textContent = item.shortcut;
        el.appendChild(sc);
      }

      if (fn) {
        stats.wired++;
        el.addEventListener('click', function (e) { e.stopPropagation(); closeAll(); fn(); });
      } else {
        stats.stubbed++;
        el.setAttribute('aria-disabled', 'true');
        el.title = STUB_TIP + ' \\u00B7 ' + item.desc;
        var flag = document.createElement('span');
        flag.className = 'hf-flag';
        flag.textContent = 'NEEDS-VERIFICATION';
        el.appendChild(flag);
        el.addEventListener('click', function (e) { e.stopPropagation(); });
      }
      return el;
    }

    MENU_DATA.forEach(function (menu, idx) {
      var top = document.createElement('div');
      top.className = 'hf-menubar-top';

      var btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'hf-menubar-btn';
      btn.setAttribute('role', 'menuitem');
      btn.setAttribute('aria-haspopup', 'menu');
      btn.setAttribute('aria-expanded', 'false');
      btn.dataset.menu = menu.id;
      var mn = mnemonics[idx];
      if (mn) {
        btn.dataset.mnemonic = mn;
        var pos = menu.menu.toUpperCase().indexOf(mn);
        btn.innerHTML = '';
        btn.appendChild(document.createTextNode(menu.menu.slice(0, pos)));
        var u = document.createElement('u');
        u.textContent = menu.menu.slice(pos, pos + 1);
        btn.appendChild(u);
        btn.appendChild(document.createTextNode(menu.menu.slice(pos + 1)));
        btn.title = menu.menu + ' (Alt+' + mn + ')';
      } else {
        btn.textContent = menu.menu;
      }

      var panel = document.createElement('div');
      panel.className = 'hf-menu';
      panel.setAttribute('role', 'menu');
      panel.setAttribute('aria-label', menu.menu + ' menu');
      panel.dataset.menu = menu.id;
      panel.hidden = true;

      menu.items.forEach(function (item) { panel.appendChild(buildItem(item, panel)); });

      var foot = document.createElement('div');
      foot.className = 'hf-menu-foot';
      foot.textContent = PROVENANCE;
      panel.appendChild(foot);

      var entry = { btn: btn, panel: panel, menu: menu };
      menuEls.push(entry);

      btn.addEventListener('click', function (e) {
        e.stopPropagation();
        if (state.openMenu === entry) closeAll();
        else openMenu(entry, false);
      });
      btn.addEventListener('mouseenter', function () {
        if (state.openMenu && state.openMenu !== entry) openMenu(entry, false);
      });

      top.appendChild(btn);
      top.appendChild(panel);
      bar.appendChild(top);
    });

    // ---- keyboard handling --------------------------------------------------
    function focusableItems(panel) {
      return Array.prototype.filter.call(
        panel.querySelectorAll('.hf-menu-item'),
        function (el) { return !el.closest('.hf-submenu') || !el.closest('.hf-submenu').hidden; }
      );
    }

    function onBarKeydown(e) {
      var entry = state.openMenu;
      if (e.key === 'Escape') {
        if (state.openSub) { state.openSub.hidden = true; state.openSub = null; if (entry) entry.btn.focus(); }
        else if (entry) { var b = entry.btn; closeAll(); b.focus(); }
        return;
      }
      var idx = menuEls.indexOf(entry);
      if (e.key === 'ArrowRight' && entry && !e.target.closest('.hf-menu')) {
        e.preventDefault(); openMenu(menuEls[(idx + 1) % menuEls.length], false); menuEls[(idx + 1) % menuEls.length].btn.focus(); return;
      }
      if (e.key === 'ArrowLeft' && entry && !e.target.closest('.hf-menu')) {
        e.preventDefault(); openMenu(menuEls[(idx - 1 + menuEls.length) % menuEls.length], false); menuEls[(idx - 1 + menuEls.length) % menuEls.length].btn.focus(); return;
      }
      if (!entry) return;
      var inPanel = e.target.closest('.hf-menu');
      var items = focusableItems(entry.panel);
      var cur = items.indexOf(document.activeElement);
      if (e.key === 'ArrowDown') {
        e.preventDefault();
        if (!inPanel) { if (items[0]) items[0].focus(); }
        else if (items.length) items[(cur + 1) % items.length].focus();
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        if (items.length) items[(cur - 1 + items.length) % items.length].focus();
      } else if (e.key === 'Home') {
        e.preventDefault(); if (items[0]) items[0].focus();
      } else if (e.key === 'End') {
        e.preventDefault(); if (items.length) items[items.length - 1].focus();
      } else if ((e.key === 'ArrowLeft' || e.key === 'ArrowRight') && inPanel) {
        // left/right inside a panel hop between menus (unless a submenu handled it)
        if (!e.defaultPrevented) {
          e.preventDefault();
          var n = e.key === 'ArrowRight' ? (idx + 1) % menuEls.length : (idx - 1 + menuEls.length) % menuEls.length;
          openMenu(menuEls[n], true);
        }
      }
    }
    bar.addEventListener('keydown', onBarKeydown);

    function onDocKeydown(e) {
      if (e.altKey && !e.ctrlKey && !e.metaKey && e.key && e.key.length === 1) {
        var ch = e.key.toUpperCase();
        for (var i = 0; i < menuEls.length; i++) {
          if (menuEls[i].btn.dataset.mnemonic === ch) {
            e.preventDefault();
            if (state.openMenu === menuEls[i]) closeAll();
            else openMenu(menuEls[i], true);
            return;
          }
        }
      }
      if (e.key === 'Escape' && state.openMenu && !bar.contains(document.activeElement)) closeAll();
    }
    function onDocClick(e) {
      if (!bar.contains(e.target)) closeAll();
    }
    document.addEventListener('keydown', onDocKeydown);
    document.addEventListener('click', onDocClick);

    container.appendChild(bar);

    return {
      el: bar,
      stats: function () { return { menus: stats.menus, items: stats.items, wired: stats.wired, stubbed: stats.stubbed, provenance: PROVENANCE }; },
      open: function (menuId) {
        for (var i = 0; i < menuEls.length; i++) {
          if (menuEls[i].menu.id === menuId) { openMenu(menuEls[i], true); return true; }
        }
        return false;
      },
      close: closeAll,
      unmount: function () {
        document.removeEventListener('keydown', onDocKeydown);
        document.removeEventListener('click', onDocClick);
        portals.forEach(function (p) { p.remove(); });
        bar.remove();
      }
    };
  }

  window.HFMenuBar = {
    version: '1.0.0',
    provenance: PROVENANCE,
    data: MENU_DATA,
    exportFormats: EXPORT_FORMATS.slice(),
    mount: mount
  };
})();
`;

fs.writeFileSync(OUT, component);
const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
console.log(`wrote ${OUT} (${kb} KB, ${menus.length} menus, ${menus.reduce((n, m) => n + m.items.length, 0)} items)`);
