/**
 * Component manifest. Each entry references a GLB in ./assets/glb/
 * (relative to the package root) and carries the structured metadata
 * needed by the placement + hydraulic calc layers.
 *
 * Phase M1: 15 authored components (via Blender MCP).
 * Phase M2+: grow to 100+ via Blender + manufacturer BIM imports.
 */

import type { CatalogEntry } from './types.js'

export const CATALOG: readonly CatalogEntry[] = [
  // ── 5 sprinkler heads ──────────────────────────────────────────────────

  {
    sku: 'SM_Head_Pendant_Standard_K56',
    name: 'Standard Pendant Sprinkler K=5.6',
    category: 'sprinkler_head_pendant',
    mounting: 'ceiling_pendent',
    manufacturer: '(generic)',
    model: 'Pendant-Standard-K5.6',
    glb_path: 'assets/glb/SM_Head_Pendant_Standard_K56.glb',
    dims_cm: [5.0, 5.0, 5.5],
    k_factor: 5.6,
    temp_rating_f: 165,
    response: 'standard',
    connection: 'npt',
    finish: 'Chrome',
    open_source: true,
  },
  {
    sku: 'SM_Head_Pendant_QR_K56',
    name: 'Quick-Response Pendant Sprinkler K=5.6',
    category: 'sprinkler_head_pendant',
    mounting: 'ceiling_pendent',
    manufacturer: '(generic)',
    model: 'Pendant-QR-K5.6',
    glb_path: 'assets/glb/SM_Head_Pendant_QR_K56.glb',
    dims_cm: [4.4, 4.4, 4.7],
    k_factor: 5.6,
    temp_rating_f: 155,
    response: 'fast',
    connection: 'npt',
    finish: 'Chrome',
    open_source: true,
  },
  {
    sku: 'SM_Head_Upright_Standard_K56',
    name: 'Standard Upright Sprinkler K=5.6',
    category: 'sprinkler_head_upright',
    mounting: 'ceiling_upright',
    manufacturer: '(generic)',
    model: 'Upright-Standard-K5.6',
    glb_path: 'assets/glb/SM_Head_Upright_Standard_K56.glb',
    dims_cm: [5.0, 5.0, 5.5],
    k_factor: 5.6,
    temp_rating_f: 165,
    response: 'standard',
    connection: 'npt',
    finish: 'Brass',
    open_source: true,
  },
  {
    sku: 'SM_Head_Sidewall_Horizontal_K56',
    name: 'Horizontal Sidewall Sprinkler K=5.6',
    category: 'sprinkler_head_sidewall',
    mounting: 'wall_mount',
    manufacturer: '(generic)',
    model: 'Sidewall-Horiz-K5.6',
    glb_path: 'assets/glb/SM_Head_Sidewall_Horizontal_K56.glb',
    dims_cm: [4.0, 5.8, 2.0],
    k_factor: 5.6,
    temp_rating_f: 165,
    response: 'standard',
    connection: 'npt',
    finish: 'Chrome',
    open_source: true,
  },
  {
    sku: 'SM_Head_Concealed_Pendant_K56',
    name: 'Concealed Pendant Sprinkler K=5.6',
    category: 'sprinkler_head_concealed',
    mounting: 'ceiling_flush',
    manufacturer: '(generic)',
    model: 'Concealed-Pendant-K5.6',
    glb_path: 'assets/glb/SM_Head_Concealed_Pendant_K56.glb',
    dims_cm: [7.0, 7.0, 6.2],
    k_factor: 5.6,
    temp_rating_f: 135,
    response: 'standard',
    connection: 'npt',
    finish: 'White cover plate',
    open_source: true,
  },

  // ── 6 pipes (SCH10 grooved, 1m unit lengths — scale on Z when placed) ──

  {
    sku: 'SM_Pipe_SCH10_1in_1m',
    name: '1" Steel SCH10 Grooved Pipe (1m)',
    category: 'pipe_steel_sch10',
    mounting: 'pipe_segment',
    manufacturer: '(generic)',
    model: 'SCH10-1in',
    glb_path: 'assets/glb/SM_Pipe_SCH10_1in_1m.glb',
    dims_cm: [3.34, 3.34, 100.0],
    pipe_size_in: 1.0,
    connection: 'grooved',
    finish: 'Red-painted steel',
    open_source: true,
  },
  {
    sku: 'SM_Pipe_SCH10_1_25in_1m',
    name: '1-1/4" Steel SCH10 Grooved Pipe (1m)',
    category: 'pipe_steel_sch10',
    mounting: 'pipe_segment',
    manufacturer: '(generic)',
    model: 'SCH10-1.25in',
    glb_path: 'assets/glb/SM_Pipe_SCH10_1_25in_1m.glb',
    dims_cm: [4.22, 4.22, 100.0],
    pipe_size_in: 1.25,
    connection: 'grooved',
    finish: 'Red-painted steel',
    open_source: true,
  },
  {
    sku: 'SM_Pipe_SCH10_1_5in_1m',
    name: '1-1/2" Steel SCH10 Grooved Pipe (1m)',
    category: 'pipe_steel_sch10',
    mounting: 'pipe_segment',
    manufacturer: '(generic)',
    model: 'SCH10-1.5in',
    glb_path: 'assets/glb/SM_Pipe_SCH10_1_5in_1m.glb',
    dims_cm: [4.83, 4.83, 100.0],
    pipe_size_in: 1.5,
    connection: 'grooved',
    finish: 'Red-painted steel',
    open_source: true,
  },
  {
    sku: 'SM_Pipe_SCH10_2in_1m',
    name: '2" Steel SCH10 Grooved Pipe (1m)',
    category: 'pipe_steel_sch10',
    mounting: 'pipe_segment',
    manufacturer: '(generic)',
    model: 'SCH10-2in',
    glb_path: 'assets/glb/SM_Pipe_SCH10_2in_1m.glb',
    dims_cm: [6.03, 6.03, 100.0],
    pipe_size_in: 2.0,
    connection: 'grooved',
    finish: 'Red-painted steel',
    open_source: true,
  },
  {
    sku: 'SM_Pipe_SCH10_2_5in_1m',
    name: '2-1/2" Steel SCH10 Grooved Pipe (1m)',
    category: 'pipe_steel_sch10',
    mounting: 'pipe_segment',
    manufacturer: '(generic)',
    model: 'SCH10-2.5in',
    glb_path: 'assets/glb/SM_Pipe_SCH10_2_5in_1m.glb',
    dims_cm: [7.30, 7.30, 100.0],
    pipe_size_in: 2.5,
    connection: 'grooved',
    finish: 'Red-painted steel',
    open_source: true,
  },
  {
    sku: 'SM_Pipe_SCH10_3in_1m',
    name: '3" Steel SCH10 Grooved Pipe (1m)',
    category: 'pipe_steel_sch10',
    mounting: 'pipe_segment',
    manufacturer: '(generic)',
    model: 'SCH10-3in',
    glb_path: 'assets/glb/SM_Pipe_SCH10_3in_1m.glb',
    dims_cm: [8.89, 8.89, 100.0],
    pipe_size_in: 3.0,
    connection: 'grooved',
    finish: 'Red-painted steel',
    open_source: true,
  },

  // ── 5 fittings ─────────────────────────────────────────────────────────

  {
    sku: 'SM_Fitting_Elbow_90_2in',
    name: '2" 90° Grooved Elbow',
    category: 'fitting_elbow_90',
    mounting: 'pipe_inline',
    manufacturer: '(generic)',
    model: 'Elbow-90-2in',
    glb_path: 'assets/glb/SM_Fitting_Elbow_90_2in.glb',
    dims_cm: [4.0, 6.0, 6.0],
    pipe_size_in: 2.0,
    connection: 'grooved',
    finish: 'Black iron',
    open_source: true,
  },
  {
    sku: 'SM_Fitting_Elbow_90_1in',
    name: '1" 90° Grooved Elbow',
    category: 'fitting_elbow_90',
    mounting: 'pipe_inline',
    manufacturer: '(generic)',
    model: 'Elbow-90-1in',
    glb_path: 'assets/glb/SM_Fitting_Elbow_90_1in.glb',
    dims_cm: [3.0, 3.4, 3.4],
    pipe_size_in: 1.0,
    connection: 'grooved',
    finish: 'Black iron',
    open_source: true,
  },
  {
    sku: 'SM_Fitting_Tee_Equal_2in',
    name: '2" Equal Grooved Tee',
    category: 'fitting_tee_equal',
    mounting: 'pipe_inline',
    manufacturer: '(generic)',
    model: 'Tee-Equal-2in',
    glb_path: 'assets/glb/SM_Fitting_Tee_Equal_2in.glb',
    dims_cm: [8.0, 6.0, 4.0],
    pipe_size_in: 2.0,
    connection: 'grooved',
    finish: 'Black iron',
    open_source: true,
  },
  {
    sku: 'SM_Fitting_Reducer_2to1',
    name: '2" × 1" Concentric Reducer',
    category: 'fitting_reducer',
    mounting: 'pipe_inline',
    manufacturer: '(generic)',
    model: 'Reducer-2to1',
    glb_path: 'assets/glb/SM_Fitting_Reducer_2to1.glb',
    dims_cm: [6.0, 6.0, 6.0],
    pipe_size_in: 2.0,
    connection: 'grooved',
    finish: 'Black iron',
    notes: 'Reduces 2" main to 1" branch',
    open_source: true,
  },
  {
    sku: 'SM_Fitting_Coupling_Grooved_2in',
    name: '2" Rigid Grooved Coupling',
    category: 'fitting_coupling_grooved',
    mounting: 'pipe_inline',
    manufacturer: '(generic)',
    model: 'Coupling-Grooved-2in',
    glb_path: 'assets/glb/SM_Fitting_Coupling_Grooved_2in.glb',
    dims_cm: [8.0, 8.0, 8.0],
    pipe_size_in: 2.0,
    connection: 'grooved',
    finish: 'Black iron',
    open_source: true,
  },

  // ── 2 valves ───────────────────────────────────────────────────────────

  {
    sku: 'SM_Valve_OSY_Gate_4in',
    name: '4" OS&Y Gate Valve',
    category: 'valve_osy_gate',
    mounting: 'pipe_inline',
    manufacturer: '(generic)',
    model: 'OSY-Gate-4in',
    glb_path: 'assets/glb/SM_Valve_OSY_Gate_4in.glb',
    dims_cm: [16.0, 18.0, 33.0],
    pipe_size_in: 4.0,
    connection: 'flanged',
    finish: 'Red-painted cast iron',
    notes: 'Main water shutoff; supervised with tamper switch',
    open_source: true,
  },
  {
    sku: 'SM_Valve_Butterfly_4in_Grooved',
    name: '4" Grooved Butterfly Valve',
    category: 'valve_butterfly',
    mounting: 'pipe_inline',
    manufacturer: '(generic)',
    model: 'Butterfly-4in-Grooved',
    glb_path: 'assets/glb/SM_Valve_Butterfly_4in_Grooved.glb',
    dims_cm: [15.0, 15.0, 16.0],
    pipe_size_in: 4.0,
    connection: 'grooved',
    finish: 'Red-painted iron',
    notes: 'Integral tamper switch',
    open_source: true,
  },

  // ── 2 riser components ─────────────────────────────────────────────────

  {
    sku: 'SM_Riser_FlowSwitch_2in',
    name: '2" Paddle-type Flow Switch',
    category: 'riser_flow_switch',
    mounting: 'pipe_inline',
    manufacturer: '(generic)',
    model: 'FlowSwitch-Paddle-2in',
    glb_path: 'assets/glb/SM_Riser_FlowSwitch_2in.glb',
    dims_cm: [6.0, 5.0, 12.0],
    pipe_size_in: 2.0,
    connection: 'npt',
    finish: 'Red-painted enclosure',
    notes: 'Potter VSR-SF class',
    open_source: true,
  },
  {
    sku: 'SM_Riser_PressureGauge',
    name: '2.5" Pressure Gauge w/ Brass Petcock',
    category: 'riser_pressure_gauge',
    mounting: 'pipe_inline',
    manufacturer: '(generic)',
    model: 'Gauge-2.5in',
    glb_path: 'assets/glb/SM_Riser_PressureGauge.glb',
    dims_cm: [7.0, 7.0, 9.0],
    connection: 'npt',
    finish: 'Brass',
    notes: '0–300 psi dial; supervised position optional',
    open_source: true,
  },
]

/** Convenience: total count for display / tests */
export const CATALOG_COUNT = CATALOG.length
