'use client'

/**
 * AutoDesignPanel — ONE button, one result.
 *
 * Replaces the 6-section click-through Fire Protection panel. The
 * agent roster does the work:
 *   1. Upload / select an architect PDF (or the embedded 1881 arch)
 *   2. Pipeline runs: intake → classify → place → route → calc →
 *      rulecheck → bom → labor → proposal → submittal
 *   3. Scene auto-renders building shell + placed heads + routed
 *      pipes as the pipeline stages finish
 *   4. Deliverables served directly from gateway
 *
 * Per AGENTIC_RULES §13: honest status every step. If intake returns
 * zero walls, the UI says so — it does NOT spawn a fake building.
 */

import { generateId, useScene } from '@pascal-app/core'
import { useCallback, useEffect, useRef, useState } from 'react'

const GATEWAY_URL =
  process.env.NEXT_PUBLIC_HALOPENCLAW_URL ?? 'http://localhost:18080'

interface Step {
  step: string
  stats?: Record<string, unknown>
  error?: string | null
}

interface JobStatus {
  job_id: string
  project_id: string
  status: 'queued' | 'running' | 'completed' | 'failed'
  percent: number
  steps_complete: string[]
  error?: string | null
  summary?: {
    project_id: string
    steps: Step[]
    files: Record<string, string>
  } | null
}

const PRESETS = [
  {
    id: 'upload',
    label: 'Upload your own architect PDF / IFC / DWG',
  },
  {
    id: '1881-architecturals',
    label: '1881 Cooperative — full architectural set (110 pages)',
    path: 'E:/ClaudeBot/HaloFireBidDocs/1-Bid Documents/GC - Bid Plans/1881 - Architecturals.pdf',
  },
  {
    id: '1881-fire-rfis',
    label: '1881 Fire RFIs (small, fast smoke test)',
    path: 'E:/ClaudeBot/HaloFireBidDocs/1-Bid Documents/GC - Bid Plans/1881 Fire RFI\'s.pdf',
  },
]

export function AutoDesignPanel({ projectId }: { projectId: string }) {
  const [preset, setPreset] = useState<string>('1881-architecturals')
  const [file, setFile] = useState<File | null>(null)
  const [job, setJob] = useState<JobStatus | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const inputRef = useRef<HTMLInputElement>(null)

  const createNode = useScene((s) => s.createNode)
  const sceneNodes = useScene((s) => s.nodes)
  const deleteNode = useScene((s) => s.deleteNode)

  /** Locate the first `level` node in the scene tree — same pattern
   *  SceneBootstrap uses. Returns undefined if the tree isn't ready
   *  yet; caller will retry on next render. */
  const findLevelId = useCallback((): string | undefined => {
    for (const n of Object.values(sceneNodes ?? {})) {
      const typed = n as { type?: string; id?: string }
      if (typed?.type === 'level' && typed.id) return typed.id
    }
    return undefined
  }, [sceneNodes])

  /** Remove any previous auto_design spawns so re-runs don't pile up. */
  const clearPreviousAutoDesign = useCallback(() => {
    for (const n of Object.values(sceneNodes ?? {})) {
      const tags = (n as { asset?: { tags?: string[] } }).asset?.tags ?? []
      if (tags.includes('auto_design')) {
        try {
          deleteNode((n as { id: string }).id)
        } catch {
          // best effort
        }
      }
    }
  }, [sceneNodes, deleteNode])

  // Cap how many heads + pipes the auto-design dumps into the live
  // viewport at once — a 583-head / 194-pipe 1881 design would swamp
  // the scene. The full set stays in design.json for the pipeline;
  // this is viewport-only throttling.
  const MAX_HEADS_VIEWPORT = 150
  const MAX_PIPES_VIEWPORT = 150

  const stopPoll = useCallback(() => {
    if (pollRef.current) {
      clearInterval(pollRef.current)
      pollRef.current = null
    }
  }, [])

  useEffect(() => () => stopPoll(), [stopPoll])

  // When pipeline completes, spawn building shell + heads + pipes
  // into the Three.js viewport automatically (no manual clicks).
  const renderResults = useCallback(
    async (pid: string) => {
      try {
        // Load the design.json (generated by the pipeline) to know
        // what to spawn.
        const res = await fetch(
          `${GATEWAY_URL}/projects/${pid}/design.json`,
        )
        if (!res.ok) return
        const design = await res.json()

        // Parent every spawned node to the active Pascal Level so
        // items show in the viewport (not orphaned under Site).
        // Same gate SceneBootstrap uses.
        const levelId = findLevelId()
        if (!levelId) {
          setError(
            'scene render: Pascal level tree not ready — try again in a moment',
          )
          return
        }
        // Fresh run — wipe any previous auto-design spawns so the
        // viewport reflects the latest pipeline output.
        clearPreviousAutoDesign()
        const levels: Array<{
          id: string
          name: string
          elevation_m: number
          height_m?: number
          use?: string
          polygon_m?: [number, number][]
        }> = design.building?.levels ?? []
        const systems: Array<{
          id: string
          heads?: Array<{
            id: string
            position_m: [number, number, number]
            sku?: string
          }>
          pipes?: Array<{
            id: string
            size_in: number
            start_m: [number, number, number]
            end_m: [number, number, number]
          }>
        }> = design.systems ?? []

        // Simple slab renderer for each level — rectangles at elevation.
        for (const lvl of levels) {
          if (!lvl.polygon_m || lvl.polygon_m.length < 3) continue
          const xs = lvl.polygon_m.map((p) => p[0])
          const ys = lvl.polygon_m.map((p) => p[1])
          const w = Math.max(1, Math.max(...xs) - Math.min(...xs))
          const d = Math.max(1, Math.max(...ys) - Math.min(...ys))
          try {
            createNode(
              {
                id: generateId('item'),
                type: 'item',
                position: [Math.min(...xs) + w / 2, lvl.elevation_m, Math.min(...ys) + d / 2],
                rotation: [0, 0, 0],
                scale: [1, 1, 1],
                children: [],
                asset: {
                  id: `slab_${lvl.id}`,
                  category: 'slab',
                  name: `${lvl.name} slab`,
                  thumbnail: '/icons/item.png',
                  dimensions: [w, 0.2, d],
                  src: '',
                  attachTo: 'floor',
                  offset: [0, 0, 0],
                  rotation: [0, 0, 0],
                  scale: [1, 1, 1],
                  tags: ['halofire', 'slab', 'auto_design'],
                },
              } as any,
              levelId,
            )
          } catch {
            // per-level spawn is best-effort; don't block others
          }
        }

        // Heads — 1 sphere per head ref'd at its 3D position.
        // Cap total heads in the viewport so a 583-head design doesn't
        // swamp the scene; the FULL set still lives in design.json.
        let headsSpawned = 0
        for (const sys of systems) {
          for (const h of sys.heads ?? []) {
            if (headsSpawned >= MAX_HEADS_VIEWPORT) break
            try {
              createNode(
                {
                  id: generateId('item'),
                  type: 'item',
                  position: h.position_m,
                  rotation: [0, 0, 0],
                  scale: [1, 1, 1],
                  children: [],
                  asset: {
                    id: `head_${h.id}`,
                    category: 'sprinkler_head_pendant',
                    name: h.sku ?? 'K5.6 head',
                    thumbnail: '/icons/item.png',
                    dimensions: [0.1, 0.1, 0.1],
                    src: '/halofire-catalog/glb/SM_Head_Pendant_Standard_K56.glb',
                    attachTo: 'ceiling',
                    offset: [0, 0, 0],
                    rotation: [0, 0, 0],
                    scale: [1, 1, 1],
                    tags: ['halofire', 'sprinkler_head_pendant', 'auto_design'],
                  },
                } as any,
                levelId,
              )
              headsSpawned++
            } catch {
              // best-effort per head
            }
          }
          if (headsSpawned >= MAX_HEADS_VIEWPORT) break
        }

        let pipesSpawned = 0
        for (const sys of systems) {
          for (const p of sys.pipes ?? []) {
            if (pipesSpawned >= MAX_PIPES_VIEWPORT) break
            try {
              const mx = (p.start_m[0] + p.end_m[0]) / 2
              const my = (p.start_m[1] + p.end_m[1]) / 2
              const mz = (p.start_m[2] + p.end_m[2]) / 2
              const dx = p.end_m[0] - p.start_m[0]
              const dy = p.end_m[1] - p.start_m[1]
              const dz = p.end_m[2] - p.start_m[2]
              const len = Math.max(
                0.01,
                Math.sqrt(dx * dx + dy * dy + dz * dz),
              )
              createNode(
                {
                  id: generateId('item'),
                  type: 'item',
                  position: [mx, my, mz],
                  rotation: [0, 0, Math.atan2(dy, dx)],
                  scale: [len, 1, 1],
                  children: [],
                  asset: {
                    id: `pipe_${p.id}`,
                    category: 'pipe_steel_sch10',
                    name: `${p.size_in}" pipe`,
                    thumbnail: '/icons/item.png',
                    dimensions: [len, p.size_in * 0.0254, p.size_in * 0.0254],
                    src: `/halofire-catalog/glb/SM_Pipe_SCH10_${String(p.size_in).replace('.', '_')}in_1m.glb`,
                    attachTo: 'ceiling',
                    offset: [0, 0, 0],
                    rotation: [0, 0, 0],
                    scale: [1, 1, 1],
                    tags: [
                      'halofire',
                      'pipe_steel_sch10',
                      `size_${p.size_in}`,
                      'auto_design',
                    ],
                  },
                } as any,
                levelId,
              )
              pipesSpawned++
            } catch {
              // best-effort
            }
          }
          if (pipesSpawned >= MAX_PIPES_VIEWPORT) break
        }
      } catch (e) {
        setError(`scene render: ${String(e)}`)
      }
    },
    [createNode, findLevelId, clearPreviousAutoDesign],
  )

  const run = useCallback(async () => {
    setBusy(true)
    setError(null)
    setJob(null)
    stopPoll()

    try {
      let uploadRes: Response
      const chosen = PRESETS.find((p) => p.id === preset)
      if (preset === 'upload') {
        if (!file) {
          throw new Error('pick a file first')
        }
        const form = new FormData()
        form.append('file', file)
        form.append('project_id', projectId)
        form.append('mode', 'pipeline')
        uploadRes = await fetch(
          `${GATEWAY_URL}/intake/upload?project_id=${projectId}`,
          { method: 'POST', body: form },
        )
      } else if (chosen?.path) {
        // Preset: just POST a JSON with server-side path. A
        // /intake/dispatch endpoint handles this flow for dev;
        // if unavailable, fall back to a client-side fetch+upload.
        uploadRes = await fetch(
          `${GATEWAY_URL}/intake/dispatch?project_id=${projectId}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              server_path: chosen.path,
              project_id: projectId,
            }),
          },
        )
      } else {
        throw new Error('no file and no preset selected')
      }

      if (!uploadRes.ok) {
        const txt = await uploadRes.text()
        throw new Error(`upload HTTP ${uploadRes.status}: ${txt.slice(0, 200)}`)
      }
      const uploadBody = await uploadRes.json()
      const jobId = uploadBody.job_id
      setJob({
        job_id: jobId,
        project_id: projectId,
        status: 'queued',
        percent: 0,
        steps_complete: [],
      })

      pollRef.current = setInterval(async () => {
        try {
          const r = await fetch(`${GATEWAY_URL}/intake/status/${jobId}`)
          if (!r.ok) return
          const s = await r.json()
          setJob(s)
          if (s.status === 'completed') {
            stopPoll()
            await renderResults(projectId)
          } else if (s.status === 'failed') {
            stopPoll()
          }
        } catch {
          // transient; keep polling
        }
      }, 2500)
    } catch (e) {
      setError(String(e))
    } finally {
      setBusy(false)
    }
  }, [preset, file, projectId, stopPoll, renderResults])

  return (
    <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 text-sm">
      <div>
        <h2 className="mb-1 text-base font-semibold">Auto-Design</h2>
        <p className="text-[11px] text-neutral-500">
          Drop an architect PDF / IFC / DWG. The agent pipeline runs:
          intake → classify → place heads → route pipes → hydraulic
          calc → rule check → BOM + labor → proposal + submittal.
          Everything renders in the viewport automatically.
        </p>
      </div>

      <div className="rounded border border-neutral-300 p-3 dark:border-neutral-700">
        <label className="block text-xs font-semibold">Source</label>
        <select
          value={preset}
          onChange={(e) => setPreset(e.target.value)}
          className="mt-1 w-full rounded border border-neutral-300 bg-neutral-50 px-2 py-1 text-xs dark:border-neutral-700 dark:bg-neutral-900"
        >
          {PRESETS.map((p) => (
            <option key={p.id} value={p.id}>
              {p.label}
            </option>
          ))}
        </select>

        {preset === 'upload' && (
          <div className="mt-2">
            <input
              ref={inputRef}
              type="file"
              accept=".pdf,.ifc,.dwg,.dxf"
              onChange={(e) => setFile(e.target.files?.[0] ?? null)}
              className="w-full text-[11px]"
            />
            {file && (
              <p className="mt-1 text-[10px] text-neutral-500">
                {file.name} · {(file.size / 1024 / 1024).toFixed(2)} MB
              </p>
            )}
          </div>
        )}

        <button
          type="button"
          disabled={busy}
          onClick={run}
          className="mt-3 w-full rounded bg-[#e8432d] px-3 py-2 text-sm font-semibold text-white hover:bg-[#c43719] disabled:opacity-50"
        >
          {busy ? 'Dispatching…' : 'Run Auto-Design'}
        </button>

        {/* Quick re-populate after a page reload — reads the last
            design.json off disk and spawns the scene nodes without
            re-running the ~3-minute pipeline. */}
        <button
          type="button"
          disabled={busy}
          onClick={() => { void renderResults(projectId) }}
          className="mt-2 w-full rounded border border-white/15 bg-transparent px-3 py-1.5 text-xs text-neutral-200 hover:bg-white/5 disabled:opacity-50"
          title="Load the last completed design into the viewport"
        >
          Render last bid
        </button>
      </div>

      {error && (
        <div className="rounded bg-red-50 p-2 text-[11px] text-red-900 dark:bg-red-950 dark:text-red-200">
          {error}
        </div>
      )}

      {job && (
        <div className="rounded border border-neutral-300 p-2 text-[11px] dark:border-neutral-700">
          <div className="flex items-center justify-between">
            <span className="font-mono text-[10px]">
              {job.job_id.slice(0, 8)}
            </span>
            <span
              className={`rounded px-2 py-0.5 font-mono text-[10px] ${
                job.status === 'completed'
                  ? 'bg-green-200 text-green-900 dark:bg-green-950 dark:text-green-300'
                  : job.status === 'failed'
                    ? 'bg-red-200 text-red-900 dark:bg-red-950 dark:text-red-300'
                    : 'bg-amber-200 text-amber-900 dark:bg-amber-950 dark:text-amber-300'
              }`}
            >
              {job.status}
            </span>
          </div>
          {job.steps_complete.length > 0 && (
            <ol className="mt-2 space-y-0.5 text-[10px] text-neutral-600 dark:text-neutral-400">
              {job.steps_complete.map((s) => (
                <li key={s} className="font-mono">
                  ✓ {s}
                </li>
              ))}
            </ol>
          )}
          {job.summary?.steps && (
            <details className="mt-1">
              <summary className="cursor-pointer text-[10px] text-neutral-500">
                Pipeline detail ({job.summary.steps.length} steps)
              </summary>
              <pre className="mt-1 max-h-60 overflow-y-auto whitespace-pre-wrap rounded bg-neutral-100 p-1 text-[9px] dark:bg-neutral-900">
                {JSON.stringify(job.summary.steps, null, 2)}
              </pre>
            </details>
          )}
          {job.error && (
            <p className="mt-1 text-red-700 dark:text-red-300">
              {job.error}
            </p>
          )}
          {job.status === 'completed' && (
            <div className="mt-2 space-y-1">
              <p className="text-[10px] font-semibold">Deliverables:</p>
              {['proposal.json', 'proposal.pdf', 'design.dxf', 'design.glb', 'design.ifc'].map((name) => (
                <a
                  key={name}
                  href={`${GATEWAY_URL}/projects/${projectId}/deliverable/${name}`}
                  target="_blank"
                  rel="noreferrer"
                  className="block rounded bg-neutral-800 px-2 py-1 text-center text-[10px] text-white hover:bg-neutral-700"
                >
                  {name}
                </a>
              ))}
              <a
                href={`/bid/${projectId}`}
                target="_blank"
                rel="noreferrer"
                className="block rounded bg-[#e8432d] px-2 py-1 text-center text-[10px] font-semibold text-white hover:bg-[#c43719]"
              >
                Open bid viewer ↗
              </a>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
